//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICATION
    {
        public APPLICATION()
        {
            this.ERROR_LOG = new HashSet<ERROR_LOG>();
        }
    
        public int APPLICATION_ID { get; set; }
        public string APPLICATION_NAME { get; set; }
        public string APPLICATION_DESC { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
    
        public virtual ICollection<ERROR_LOG> ERROR_LOG { get; set; }
    }
}
