//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTHORIZATION_TYPE
    {
        public AUTHORIZATION_TYPE()
        {
            this.CANDIDATE_COMMITTEE_AUTH = new HashSet<CANDIDATE_COMMITTEE_AUTH>();
            this.CANDIDATE_AUTH_HISTORY = new HashSet<CANDIDATE_AUTH_HISTORY>();
        }
    
        public int AUTH_TYPE_ID { get; set; }
        public string AUTH_TYPE_DESC { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<CANDIDATE_COMMITTEE_AUTH> CANDIDATE_COMMITTEE_AUTH { get; set; }
        public virtual ICollection<CANDIDATE_AUTH_HISTORY> CANDIDATE_AUTH_HISTORY { get; set; }
    }
}
