//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTHORIZED_SIGNATORY
    {
        public int AUTH_SIGN_ID { get; set; }
        public long PERSON_ID { get; set; }
        public long COMM_ID { get; set; }
        public System.DateTime AUTH_SIGN_DATE_FROM { get; set; }
        public Nullable<System.DateTime> AUTH_SIGN_DATE_TO { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual COMMITTEE COMMITTEE { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
