//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class awsdms_truncation_safeguard
    {
        public string latchTaskName { get; set; }
        public string latchMachineGUID { get; set; }
        public string LatchKey { get; set; }
        public System.DateTime latchLocker { get; set; }
    }
}
