//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BALLOT_PROPOSALS
    {
        public BALLOT_PROPOSALS()
        {
            this.COMMITTEE_PURPOSE = new HashSet<COMMITTEE_PURPOSE>();
        }
    
        public int BALLOT_PROP_ID { get; set; }
        public int ELECT_ID { get; set; }
        public string BALLOT_DESC { get; set; }
        public string R_RECORD_CREATED { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<long> PET_ID { get; set; }
        public Nullable<int> BALLOT_PROP_TYPE_ID { get; set; }
        public Nullable<int> BALLOT_PROP_ORDER { get; set; }
        public string BALLOT_PROP_HEADER { get; set; }
        public string BALLOT_PROP_TITLE { get; set; }
    
        public virtual BALLOT_PROPOSAL_TYPE BALLOT_PROPOSAL_TYPE { get; set; }
        public virtual ICollection<COMMITTEE_PURPOSE> COMMITTEE_PURPOSE { get; set; }
        public virtual ELECTION ELECTION { get; set; }
        public virtual PETITION PETITION { get; set; }
    }
}
