//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BALLOT_CORRESPONDENCE
    {
        public long BALLOT_CORR_ID { get; set; }
        public Nullable<long> ELECT_CAND_ID { get; set; }
        public Nullable<long> PET_ID { get; set; }
        public Nullable<int> PET_FRM_MAP_ID { get; set; }
        public int CORES_TYPE_ID { get; set; }
        public Nullable<System.DateTime> ACCEPTANCE_DUE_DATE { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<long> PERSON_ID { get; set; }
        public Nullable<System.DateTime> BALLOT_DRAWING_DATETIME { get; set; }
    
        public virtual ELECTION_CANDIDATE ELECTION_CANDIDATE { get; set; }
        public virtual PETITION PETITION { get; set; }
        public virtual PETITION_FORM_MAPPING PETITION_FORM_MAPPING { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
