//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BALLOT_ORDER
    {
        public BALLOT_ORDER()
        {
            this.ELECTION_CANDIDATE_HISTORY = new HashSet<ELECTION_CANDIDATE_HISTORY>();
        }
    
        public int BALLOT_ORDER_ID { get; set; }
        public int PARTY_ELECT_ID { get; set; }
        public Nullable<int> BALLOT_SORT_ORD { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<ELECTION_CANDIDATE_HISTORY> ELECTION_CANDIDATE_HISTORY { get; set; }
    }
}
