//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMPAIGN_MATERIAL
    {
        public int CAMP_MATR_ID { get; set; }
        public long FILINGS_ID { get; set; }
        public Nullable<int> FILING_METHOD_ID { get; set; }
        public System.DateTime DATE_SUBMITTED { get; set; }
        public Nullable<long> SCAN_DOC_ID { get; set; }
        public string CAMP_MATR_DESC { get; set; }
        public string CAMP_MATR_FILE_TYPE { get; set; }
        public string CAMP_MATR_FILE_SIZE { get; set; }
        public string R_CAMP_MATR { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string R_AMEND { get; set; }
    
        public virtual FILING FILING { get; set; }
        public virtual FILING_METHOD FILING_METHOD { get; set; }
    }
}
