//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANDIDATE_HISTORY
    {
        public int CAND_HIST_ID { get; set; }
        public Nullable<long> FILER_ID { get; set; }
        public long CAND_ID { get; set; }
        public long ELECT_CAND_ID { get; set; }
        public Nullable<int> MASTER_TYPE_ID { get; set; }
        public Nullable<int> COUNTY_ID { get; set; }
        public Nullable<int> AUTH_KEY { get; set; }
        public Nullable<System.DateTime> CAND_REG_DATE { get; set; }
        public Nullable<System.DateTime> CAND_TERM_DATE { get; set; }
        public string COUNTY_CANDIDATE_ID { get; set; }
        public string R_CAND_COMM_EXIST { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual CANDIDATE CANDIDATE { get; set; }
        public virtual COUNTY COUNTY { get; set; }
        public virtual ELECTION_CANDIDATE ELECTION_CANDIDATE { get; set; }
        public virtual REQUIRED_FILER REQUIRED_FILER { get; set; }
        public virtual MASTER_TYPE MASTER_TYPE { get; set; }
    }
}
