//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANDIDATE
    {
        public CANDIDATE()
        {
            this.ELECTION_CANDIDATE = new HashSet<ELECTION_CANDIDATE>();
            this.CANDIDATE_COMMITTEE = new HashSet<CANDIDATE_COMMITTEE>();
            this.CANDIDATE_HISTORY = new HashSet<CANDIDATE_HISTORY>();
            this.REQUIRED_FILER = new HashSet<REQUIRED_FILER>();
        }
    
        public long CAND_ID { get; set; }
        public long PERSON_ID { get; set; }
        public Nullable<int> MASTER_TYPE_ID { get; set; }
        public Nullable<int> COUNTY_ID { get; set; }
        public Nullable<int> AUTH_KEY { get; set; }
        public Nullable<System.DateTime> CAND_REG_DATE { get; set; }
        public string R_CAND_COMM_EXIST { get; set; }
        public string COUNTY_CANDIDATE_ID { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<ELECTION_CANDIDATE> ELECTION_CANDIDATE { get; set; }
        public virtual ICollection<CANDIDATE_COMMITTEE> CANDIDATE_COMMITTEE { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual ICollection<CANDIDATE_HISTORY> CANDIDATE_HISTORY { get; set; }
        public virtual PERSON PERSON1 { get; set; }
        public virtual ICollection<REQUIRED_FILER> REQUIRED_FILER { get; set; }
    }
}
