//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANDIDATE_COMMITTEE
    {
        public CANDIDATE_COMMITTEE()
        {
            this.CANDIDATE_COMMITTEE_AUTH = new HashSet<CANDIDATE_COMMITTEE_AUTH>();
            this.FILER_SCAN_MAPPING = new HashSet<FILER_SCAN_MAPPING>();
        }
    
        public long CAND_COMM_ID { get; set; }
        public Nullable<int> MASTER_TYPE_ID { get; set; }
        public Nullable<long> CAND_ID { get; set; }
        public Nullable<long> ELECT_CAND_ID { get; set; }
        public long COMM_ID { get; set; }
        public int COMM_PURPOSE_TYPE_ID { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual CANDIDATE CANDIDATE { get; set; }
        public virtual ICollection<CANDIDATE_COMMITTEE_AUTH> CANDIDATE_COMMITTEE_AUTH { get; set; }
        public virtual ICollection<FILER_SCAN_MAPPING> FILER_SCAN_MAPPING { get; set; }
        public virtual COMMITTEE COMMITTEE { get; set; }
        public virtual COMM_PURPOSE_TYPE COMM_PURPOSE_TYPE { get; set; }
        public virtual ELECTION_CANDIDATE ELECTION_CANDIDATE { get; set; }
        public virtual MASTER_TYPE MASTER_TYPE { get; set; }
    }
}
