//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANDIDATE_COMMITTEE_AUTH
    {
        public CANDIDATE_COMMITTEE_AUTH()
        {
            this.CANDIDATE_AUTH_HISTORY = new HashSet<CANDIDATE_AUTH_HISTORY>();
        }
    
        public int CAND_COMM_AUTH_ID { get; set; }
        public long CAND_COMM_ID { get; set; }
        public int SUPPORT_DOC_ID { get; set; }
        public Nullable<int> AUTH_TYPE_ID { get; set; }
        public string R_AUTHORIZED { get; set; }
        public string R_TREAS_VERIFIED { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual AUTHORIZATION_TYPE AUTHORIZATION_TYPE { get; set; }
        public virtual ICollection<CANDIDATE_AUTH_HISTORY> CANDIDATE_AUTH_HISTORY { get; set; }
        public virtual CANDIDATE_COMMITTEE CANDIDATE_COMMITTEE { get; set; }
        public virtual SUPPORTING_DOCUMENTS SUPPORTING_DOCUMENTS { get; set; }
    }
}
