//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPAS_PET_DEF_REG
    {
        public int CAPAS_PET_DEF_REG_ID { get; set; }
        public long PET_ID { get; set; }
        public int PET_REVIEW_ID { get; set; }
        public int CAPAS_DEF_REG_ID { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual CAPAS_DEFICIENCY_REGULATIONS CAPAS_DEFICIENCY_REGULATIONS { get; set; }
        public virtual PETITION PETITION { get; set; }
        public virtual PETITION_REVIEW PETITION_REVIEW { get; set; }
    }
}
