//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPAS_DEFICIENCY_REGULATIONS
    {
        public CAPAS_DEFICIENCY_REGULATIONS()
        {
            this.CAPAS_PET_DEF_REG = new HashSet<CAPAS_PET_DEF_REG>();
        }
    
        public int CAPAS_DEF_REG_ID { get; set; }
        public string BASIS_OF_NON_COMP { get; set; }
        public string REGULATION { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<CAPAS_PET_DEF_REG> CAPAS_PET_DEF_REG { get; set; }
    }
}
