//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMM_PURPOSE_TYPE
    {
        public COMM_PURPOSE_TYPE()
        {
            this.CANDIDATE_COMMITTEE = new HashSet<CANDIDATE_COMMITTEE>();
            this.COMMITTEE_PURPOSE = new HashSet<COMMITTEE_PURPOSE>();
            this.IE_COMM_SUPPORT_OPPOSE = new HashSet<IE_COMM_SUPPORT_OPPOSE>();
        }
    
        public int COMM_PURPOSE_TYPE_ID { get; set; }
        public string PURPOSE_TYPE_DESC { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<CANDIDATE_COMMITTEE> CANDIDATE_COMMITTEE { get; set; }
        public virtual ICollection<COMMITTEE_PURPOSE> COMMITTEE_PURPOSE { get; set; }
        public virtual ICollection<IE_COMM_SUPPORT_OPPOSE> IE_COMM_SUPPORT_OPPOSE { get; set; }
    }
}
