//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMM_EMPLOYER
    {
        public long COMM_EMPLOYER_ID { get; set; }
        public Nullable<long> COMM_OP_IND_ID { get; set; }
        public Nullable<long> COMM_PAC_IND_ID { get; set; }
        public string EMPLOYER_NAME { get; set; }
        public long ADDR_ID { get; set; }
        public string REASON { get; set; }
        public string EMPLOYER_TYPE { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ADDRESS ADDRESS { get; set; }
        public virtual COMM_OPERATIONAL_INDIVIDUAL COMM_OPERATIONAL_INDIVIDUAL { get; set; }
        public virtual COMM_PAC_INDIVIDUAL COMM_PAC_INDIVIDUAL { get; set; }
    }
}
