//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMITTEE_HISTORY
    {
        public long COMM_HIST_ID { get; set; }
        public long COMM_ID { get; set; }
        public Nullable<int> MASTER_TYPE_ID { get; set; }
        public Nullable<long> PERSON_ID { get; set; }
        public long TREAS_ID { get; set; }
        public int COMM_TYPE_ID { get; set; }
        public Nullable<int> COUNTY_ID { get; set; }
        public int OFFICE_TYPE_ID { get; set; }
        public Nullable<int> OFFICE_ID { get; set; }
        public Nullable<int> MUNICIPALITY_ID { get; set; }
        public Nullable<int> PARTY_ELECT_ID { get; set; }
        public Nullable<int> OFF_DIST_MAP_ID { get; set; }
        public System.DateTime COMM_REG_DATE { get; set; }
        public Nullable<System.DateTime> COMM_TERM_DATE { get; set; }
        public string COMM_NAME { get; set; }
        public string COMM_ACRONYMS { get; set; }
        public string COMM_FEIN { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
    
        public virtual COMMITTEE COMMITTEE { get; set; }
        public virtual COMMITTEE_TYPE COMMITTEE_TYPE { get; set; }
        public virtual COUNTY COUNTY { get; set; }
        public virtual OFFICE_DISTRICT_MAPPING OFFICE_DISTRICT_MAPPING { get; set; }
        public virtual MASTER_TYPE MASTER_TYPE { get; set; }
        public virtual MUNICIPALITY MUNICIPALITY { get; set; }
        public virtual OFFICE OFFICE { get; set; }
        public virtual OFFICE_TYPE OFFICE_TYPE { get; set; }
        public virtual PARTY_ELECTION PARTY_ELECTION { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual TREASURER TREASURER { get; set; }
    }
}
