//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMITTEE_TREASURER_MAPPING
    {
        public long COMM_TREAS_MAP_ID { get; set; }
        public long COMM_ID { get; set; }
        public long TREAS_ID { get; set; }
        public System.DateTime TREAS_REG_DATE { get; set; }
        public Nullable<System.DateTime> TREAS_RESGN_DATE { get; set; }
        public string TREAS_OCCUPATION { get; set; }
        public string TREAS_EMPLOYER { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string R_CREATE_USER_ID { get; set; }
    
        public virtual COMMITTEE COMMITTEE { get; set; }
        public virtual TREASURER TREASURER { get; set; }
    }
}
