//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENT
    {
        public COMMENT()
        {
            this.FILER_COMMENTS_MAPPING = new HashSet<FILER_COMMENTS_MAPPING>();
            this.TERMINATION_DETAILS = new HashSet<TERMINATION_DETAILS>();
            this.TERMINATION_REVIEW = new HashSet<TERMINATION_REVIEW>();
            this.REVIEW_DETAILS = new HashSet<REVIEW_DETAILS>();
            this.ESCROW_TRANSACTIONS = new HashSet<ESCROW_TRANSACTIONS>();
            this.FILING_EXEMPTION_DETAILS = new HashSet<FILING_EXEMPTION_DETAILS>();
            this.REVIEW_COMPLIANCE_COMMENT_MAP = new HashSet<REVIEW_COMPLIANCE_COMMENT_MAP>();
            this.COMPLIANCE_REVIEW_MAP = new HashSet<COMPLIANCE_REVIEW_MAP>();
            this.COURT_HEARING = new HashSet<COURT_HEARING>();
            this.ELECTION_CAND_MATCH = new HashSet<ELECTION_CAND_MATCH>();
            this.HEARINGs = new HashSet<HEARING>();
            this.OBJECTIONS = new HashSet<OBJECTION>();
            this.PET_COMMENTS_MAPPING = new HashSet<PET_COMMENTS_MAPPING>();
            this.PET_FORM_COMMENTS_MAPPING = new HashSet<PET_FORM_COMMENTS_MAPPING>();
            this.SBOE_RECOMMENDATIONS_DECISION = new HashSet<SBOE_RECOMMENDATIONS_DECISION>();
            this.FILING_EXEMPTION_REVIEW = new HashSet<FILING_EXEMPTION_REVIEW>();
        }
    
        public long COMMENT_ID { get; set; }
        public string COMMENT_DESC { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<FILER_COMMENTS_MAPPING> FILER_COMMENTS_MAPPING { get; set; }
        public virtual ICollection<TERMINATION_DETAILS> TERMINATION_DETAILS { get; set; }
        public virtual ICollection<TERMINATION_REVIEW> TERMINATION_REVIEW { get; set; }
        public virtual ICollection<REVIEW_DETAILS> REVIEW_DETAILS { get; set; }
        public virtual ICollection<ESCROW_TRANSACTIONS> ESCROW_TRANSACTIONS { get; set; }
        public virtual ICollection<FILING_EXEMPTION_DETAILS> FILING_EXEMPTION_DETAILS { get; set; }
        public virtual ICollection<REVIEW_COMPLIANCE_COMMENT_MAP> REVIEW_COMPLIANCE_COMMENT_MAP { get; set; }
        public virtual ICollection<COMPLIANCE_REVIEW_MAP> COMPLIANCE_REVIEW_MAP { get; set; }
        public virtual ICollection<COURT_HEARING> COURT_HEARING { get; set; }
        public virtual ICollection<ELECTION_CAND_MATCH> ELECTION_CAND_MATCH { get; set; }
        public virtual ICollection<HEARING> HEARINGs { get; set; }
        public virtual ICollection<OBJECTION> OBJECTIONS { get; set; }
        public virtual ICollection<PET_COMMENTS_MAPPING> PET_COMMENTS_MAPPING { get; set; }
        public virtual ICollection<PET_FORM_COMMENTS_MAPPING> PET_FORM_COMMENTS_MAPPING { get; set; }
        public virtual ICollection<SBOE_RECOMMENDATIONS_DECISION> SBOE_RECOMMENDATIONS_DECISION { get; set; }
        public virtual ICollection<FILING_EXEMPTION_REVIEW> FILING_EXEMPTION_REVIEW { get; set; }
    }
}
