//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMM_PAC_INDIVIDUAL
    {
        public COMM_PAC_INDIVIDUAL()
        {
            this.COMM_EMPLOYER = new HashSet<COMM_EMPLOYER>();
        }
    
        public long COMM_PAC_IND_ID { get; set; }
        public long FILER_ID { get; set; }
        public long PERSON_ID { get; set; }
        public long ADDR_ID { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ADDRESS ADDRESS { get; set; }
        public virtual ICollection<COMM_EMPLOYER> COMM_EMPLOYER { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual REQUIRED_FILER REQUIRED_FILER { get; set; }
    }
}
