//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMITTEE_TYPE
    {
        public COMMITTEE_TYPE()
        {
            this.COMMITTEEs = new HashSet<COMMITTEE>();
            this.COMMITTEE_HISTORY = new HashSet<COMMITTEE_HISTORY>();
            this.FILING_SCHEDULE_COMM_MAPPING = new HashSet<FILING_SCHEDULE_COMM_MAPPING>();
            this.FILING_CATEGORY_COMM_MAPPING = new HashSet<FILING_CATEGORY_COMM_MAPPING>();
            this.COMPLIANCE_REVIEW_DETAILS = new HashSet<COMPLIANCE_REVIEW_DETAILS>();
        }
    
        public int COMM_TYPE_ID { get; set; }
        public string COMM_TYPE_CODE { get; set; }
        public string COMM_TYPE_DESC { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<COMMITTEE> COMMITTEEs { get; set; }
        public virtual ICollection<COMMITTEE_HISTORY> COMMITTEE_HISTORY { get; set; }
        public virtual ICollection<FILING_SCHEDULE_COMM_MAPPING> FILING_SCHEDULE_COMM_MAPPING { get; set; }
        public virtual ICollection<FILING_CATEGORY_COMM_MAPPING> FILING_CATEGORY_COMM_MAPPING { get; set; }
        public virtual ICollection<COMPLIANCE_REVIEW_DETAILS> COMPLIANCE_REVIEW_DETAILS { get; set; }
    }
}
