//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPLIANCE_REVIEW_MAP
    {
        public COMPLIANCE_REVIEW_MAP()
        {
            this.DETAILS_MAPPING = new HashSet<DETAILS_MAPPING>();
        }
    
        public int COMP_REVIEW_MAP_ID { get; set; }
        public int COMP_REVIEW_ID { get; set; }
        public long COMMENT_ID { get; set; }
        public string REVIEWER_NAME { get; set; }
        public System.DateTime REVIEW_DATE { get; set; }
        public string R_AMENDMENT { get; set; }
        public string R_DEFICIENCIES { get; set; }
        public string R_TRAINING { get; set; }
        public string R_COMPLIANT { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual COMMENT COMMENT { get; set; }
        public virtual COMPLIANCE_REVIEW COMPLIANCE_REVIEW { get; set; }
        public virtual ICollection<DETAILS_MAPPING> DETAILS_MAPPING { get; set; }
    }
}
