//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPLIANCE_REVIEW_ITEMS
    {
        public COMPLIANCE_REVIEW_ITEMS()
        {
            this.COMPLIANCE_REVIEW_DETAILS = new HashSet<COMPLIANCE_REVIEW_DETAILS>();
        }
    
        public int COMP_REVIEW_ITEM_ID { get; set; }
        public string COMP_REVIEW_ITEM_DESC { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<COMPLIANCE_REVIEW_DETAILS> COMPLIANCE_REVIEW_DETAILS { get; set; }
    }
}
