//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPLIANCE_REVIEW
    {
        public COMPLIANCE_REVIEW()
        {
            this.COMPLIANCE_REVIEW_MAP = new HashSet<COMPLIANCE_REVIEW_MAP>();
            this.DETAILS_MAPPING = new HashSet<DETAILS_MAPPING>();
        }
    
        public int COMP_REVIEW_ID { get; set; }
        public int COMP_REVIEW_DETAIL_ID { get; set; }
        public int COMP_REVIEW_TYPE_ID { get; set; }
        public long FILING_TRANS_ID { get; set; }
        public int EMP_ID { get; set; }
        public string COMP_RESULT { get; set; }
        public string COMP_INSTRUCTION { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<COMPLIANCE_REVIEW_MAP> COMPLIANCE_REVIEW_MAP { get; set; }
        public virtual COMPLIANCE_REVIEW_DETAILS COMPLIANCE_REVIEW_DETAILS { get; set; }
        public virtual COMPLIANCE_REVIEW_TYPES COMPLIANCE_REVIEW_TYPES { get; set; }
        public virtual ICollection<DETAILS_MAPPING> DETAILS_MAPPING { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual FILING_TRANSACTIONS FILING_TRANSACTIONS { get; set; }
    }
}
