//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRIBUTOR_TYPE
    {
        public CONTRIBUTOR_TYPE()
        {
            this.FILING_TRANSACTIONS_ENCRYPTED = new HashSet<FILING_TRANSACTIONS_ENCRYPTED>();
            this.FILING_TRANSACTIONS_HISTORY = new HashSet<FILING_TRANSACTIONS_HISTORY>();
        }
    
        public int CNTRBR_TYPE_ID { get; set; }
        public string CNTRBR_TYPE_DESC { get; set; }
        public string CNTRBR_TYPE_ABBREV { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<FILING_TRANSACTIONS_ENCRYPTED> FILING_TRANSACTIONS_ENCRYPTED { get; set; }
        public virtual ICollection<FILING_TRANSACTIONS_HISTORY> FILING_TRANSACTIONS_HISTORY { get; set; }
    }
}
