//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT
    {
        public CONTACT()
        {
            this.BANKs = new HashSet<BANK>();
            this.CANDIDATE_CONTACT_MAPPING = new HashSet<CANDIDATE_CONTACT_MAPPING>();
            this.COUNTY_CONTACT_MAPPING = new HashSet<COUNTY_CONTACT_MAPPING>();
            this.ELECTION_CAND_CONTACT_MAPPING = new HashSet<ELECTION_CAND_CONTACT_MAPPING>();
            this.PERSON_CONTACT_MAPPING = new HashSet<PERSON_CONTACT_MAPPING>();
        }
    
        public int CONTACT_ID { get; set; }
        public Nullable<long> PERSON_ID { get; set; }
        public int BEST_CONTACT_ID { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public string FAX { get; set; }
        public string URL_STATUS { get; set; }
        public string URL { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string CELL_PHONE { get; set; }
    
        public virtual ICollection<BANK> BANKs { get; set; }
        public virtual BEST_CONTACT BEST_CONTACT { get; set; }
        public virtual ICollection<CANDIDATE_CONTACT_MAPPING> CANDIDATE_CONTACT_MAPPING { get; set; }
        public virtual ICollection<COUNTY_CONTACT_MAPPING> COUNTY_CONTACT_MAPPING { get; set; }
        public virtual ICollection<ELECTION_CAND_CONTACT_MAPPING> ELECTION_CAND_CONTACT_MAPPING { get; set; }
        public virtual ICollection<PERSON_CONTACT_MAPPING> PERSON_CONTACT_MAPPING { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
