//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNTY
    {
        public COUNTY()
        {
            this.CANDIDATE_HISTORY = new HashSet<CANDIDATE_HISTORY>();
            this.COMMITTEEs = new HashSet<COMMITTEE>();
            this.COMMITTEE_HISTORY = new HashSet<COMMITTEE_HISTORY>();
            this.ELECTION_CANDIDATE_HISTORY = new HashSet<ELECTION_CANDIDATE_HISTORY>();
            this.MUNICIPALITies = new HashSet<MUNICIPALITY>();
            this.POLITICAL_CALENDAR_DATES = new HashSet<POLITICAL_CALENDAR_DATES>();
            this.COUNTY_CONTACT_MAPPING = new HashSet<COUNTY_CONTACT_MAPPING>();
            this.ENROLLMENT_COUNTY = new HashSet<ENROLLMENT_COUNTY>();
            this.ENROLLMENT_DISTRICT = new HashSet<ENROLLMENT_DISTRICT>();
            this.ENROLLMENT_ED = new HashSet<ENROLLMENT_ED>();
            this.ENROLLMENTs = new HashSet<ENROLLMENT>();
            this.FILING_PERIOD_CTY_MAPPING = new HashSet<FILING_PERIOD_CTY_MAPPING>();
            this.VOTER_REG_FORM_REQUEST = new HashSet<VOTER_REG_FORM_REQUEST>();
            this.COUNTY_OFFICIALS = new HashSet<COUNTY_OFFICIALS>();
            this.ELECTION_CANDIDATE = new HashSet<ELECTION_CANDIDATE>();
            this.ELECTION_DATA_DEFAULT = new HashSet<ELECTION_DATA_DEFAULT>();
            this.PARTY_CALL = new HashSet<PARTY_CALL>();
            this.VOTER_REG_REQUEST = new HashSet<VOTER_REG_REQUEST>();
        }
    
        public int COUNTY_ID { get; set; }
        public long ADDR_ID { get; set; }
        public string CNTY_DESC { get; set; }
        public string CNTY_DMV_ABRV { get; set; }
        public string CNTY_BOARD { get; set; }
        public string CNTY_REGION { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ADDRESS ADDRESS { get; set; }
        public virtual ADDRESS ADDRESS1 { get; set; }
        public virtual ICollection<CANDIDATE_HISTORY> CANDIDATE_HISTORY { get; set; }
        public virtual ICollection<COMMITTEE> COMMITTEEs { get; set; }
        public virtual ICollection<COMMITTEE_HISTORY> COMMITTEE_HISTORY { get; set; }
        public virtual ICollection<ELECTION_CANDIDATE_HISTORY> ELECTION_CANDIDATE_HISTORY { get; set; }
        public virtual ICollection<MUNICIPALITY> MUNICIPALITies { get; set; }
        public virtual ICollection<POLITICAL_CALENDAR_DATES> POLITICAL_CALENDAR_DATES { get; set; }
        public virtual ICollection<COUNTY_CONTACT_MAPPING> COUNTY_CONTACT_MAPPING { get; set; }
        public virtual ICollection<ENROLLMENT_COUNTY> ENROLLMENT_COUNTY { get; set; }
        public virtual ICollection<ENROLLMENT_DISTRICT> ENROLLMENT_DISTRICT { get; set; }
        public virtual ICollection<ENROLLMENT_ED> ENROLLMENT_ED { get; set; }
        public virtual ICollection<ENROLLMENT> ENROLLMENTs { get; set; }
        public virtual ICollection<FILING_PERIOD_CTY_MAPPING> FILING_PERIOD_CTY_MAPPING { get; set; }
        public virtual ICollection<VOTER_REG_FORM_REQUEST> VOTER_REG_FORM_REQUEST { get; set; }
        public virtual ICollection<COUNTY_OFFICIALS> COUNTY_OFFICIALS { get; set; }
        public virtual ICollection<ELECTION_CANDIDATE> ELECTION_CANDIDATE { get; set; }
        public virtual ICollection<ELECTION_DATA_DEFAULT> ELECTION_DATA_DEFAULT { get; set; }
        public virtual ICollection<PARTY_CALL> PARTY_CALL { get; set; }
        public virtual ICollection<VOTER_REG_REQUEST> VOTER_REG_REQUEST { get; set; }
    }
}
