//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURT_HEARING
    {
        public long COURT_HEARING_ID { get; set; }
        public int COURT_TYPE_ID { get; set; }
        public Nullable<long> COMMENT_ID { get; set; }
        public System.DateTime HEARING_DATE { get; set; }
        public string HEARING_STATUS { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<long> ELECT_CAND_ID { get; set; }
    
        public virtual COMMENT COMMENT { get; set; }
        public virtual COURT_TYPE COURT_TYPE { get; set; }
        public virtual ELECTION_CANDIDATE ELECTION_CANDIDATE { get; set; }
    }
}
