//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURT_TYPE
    {
        public COURT_TYPE()
        {
            this.COURT_HEARING = new HashSet<COURT_HEARING>();
        }
    
        public int COURT_TYPE_ID { get; set; }
        public string COURT_TYPE_DESC { get; set; }
    
        public virtual ICollection<COURT_HEARING> COURT_HEARING { get; set; }
    }
}
