//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CAPASFIDASTEMPEntities1 : DbContext
    {
        public CAPASFIDASTEMPEntities1()
            : base("name=CAPASFIDASTEMPEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FILING_TRANSACTIONS> FILING_TRANSACTIONS { get; set; }
        public virtual DbSet<ROLE> ROLEs { get; set; }
        public virtual DbSet<FILER_SECURITY> FILER_SECURITY { get; set; }
    
        [DbFunction("CAPASFIDASTEMPEntities1", "fn_filer_edit")]
        public virtual IQueryable<fn_filer_edit_Result> fn_filer_edit(Nullable<long> iD, string type)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_filer_edit_Result>("[CAPASFIDASTEMPEntities1].[fn_filer_edit](@ID, @Type)", iDParameter, typeParameter);
        }
    
        [DbFunction("CAPASFIDASTEMPEntities1", "fn_filer_security")]
        public virtual IQueryable<fn_filer_security_Result> fn_filer_security()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_filer_security_Result>("[CAPASFIDASTEMPEntities1].[fn_filer_security]()");
        }
    
        [DbFunction("CAPASFIDASTEMPEntities1", "fn_filer_view")]
        public virtual IQueryable<fn_filer_view_Result> fn_filer_view(Nullable<long> iD, string type)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_filer_view_Result>("[CAPASFIDASTEMPEntities1].[fn_filer_view](@ID, @Type)", iDParameter, typeParameter);
        }
    
        public virtual ObjectResult<SP_S_GetAuthorizedFiler_Result> SP_S_GetAuthorizedFiler(string uSER_ID)
        {
            var uSER_IDParameter = uSER_ID != null ?
                new ObjectParameter("USER_ID", uSER_ID) :
                new ObjectParameter("USER_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_S_GetAuthorizedFiler_Result>("SP_S_GetAuthorizedFiler", uSER_IDParameter);
        }
    }
}
