//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CAPASFIDAS_RLSEntities : DbContext
    {
        public CAPASFIDAS_RLSEntities()
            : base("name=CAPASFIDAS_RLSEntities")
        {
            this.SetCommandTimeOut(300);
        }

        public void SetCommandTimeOut(int Timeout)
        {
            var objectContext = (this as IObjectContextAdapter).ObjectContext;
            objectContext.CommandTimeout = Timeout;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FILING_TRANSACTIONS> FILING_TRANSACTIONS { get; set; }
        public virtual DbSet<ROLE> ROLEs { get; set; }
        public virtual DbSet<FILER_SECURITY> FILER_SECURITY { get; set; }
    }
}
