//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELECTION_CANDIDATE
    {
        public ELECTION_CANDIDATE()
        {
            this.BALLOT_CORRESPONDENCE = new HashSet<BALLOT_CORRESPONDENCE>();
            this.BANK_MAPPING = new HashSet<BANK_MAPPING>();
            this.CANDIDATE_COMMITTEE = new HashSet<CANDIDATE_COMMITTEE>();
            this.CANDIDATE_CONTACT_MAPPING = new HashSet<CANDIDATE_CONTACT_MAPPING>();
            this.CANDIDATE_HISTORY = new HashSet<CANDIDATE_HISTORY>();
            this.COURT_HEARING = new HashSet<COURT_HEARING>();
            this.ELECTION_CAND_ADDR_MAPPING = new HashSet<ELECTION_CAND_ADDR_MAPPING>();
            this.ELECTION_CAND_CONTACT_MAPPING = new HashSet<ELECTION_CAND_CONTACT_MAPPING>();
            this.ELECTION_CAND_DOCUMENTATION = new HashSet<ELECTION_CAND_DOCUMENTATION>();
            this.ELECTION_CAND_MAPPING = new HashSet<ELECTION_CAND_MAPPING>();
            this.ELECTION_CAND_NAME_MAPPING = new HashSet<ELECTION_CAND_NAME_MAPPING>();
            this.ELECTION_CAND_SIGNATURE = new HashSet<ELECTION_CAND_SIGNATURE>();
            this.FILER_COMMENTS_MAPPING = new HashSet<FILER_COMMENTS_MAPPING>();
            this.FILER_ELECTION_CAND_MAPPING = new HashSet<FILER_ELECTION_CAND_MAPPING>();
            this.FILER_HOLD_HISTORY = new HashSet<FILER_HOLD_HISTORY>();
            this.PETITION_FORM_MAPPING = new HashSet<PETITION_FORM_MAPPING>();
            this.PETITION_FORM_MAPPING1 = new HashSet<PETITION_FORM_MAPPING>();
            this.SBOE_RECOMMENDATIONS_DECISION = new HashSet<SBOE_RECOMMENDATIONS_DECISION>();
            this.SUPPORTED_CANDIDATE_MAPPING = new HashSet<SUPPORTED_CANDIDATE_MAPPING>();
            this.SUPPORTED_CANDIDATE_MAPPING1 = new HashSet<SUPPORTED_CANDIDATE_MAPPING>();
            this.SUPPORTING_DOCUMENTS = new HashSet<SUPPORTING_DOCUMENTS>();
        }
    
        public long ELECT_CAND_ID { get; set; }
        public int ELECT_ID { get; set; }
        public long CAND_ID { get; set; }
        public Nullable<long> TREAS_ID { get; set; }
        public Nullable<int> MUNICIPALITY_ID { get; set; }
        public Nullable<int> COUNTY_ID { get; set; }
        public Nullable<int> OFF_DIST_MAP_ID { get; set; }
        public Nullable<int> OFF_DIST_MAP_ID2 { get; set; }
        public Nullable<int> BALLOT_TYPE_ID { get; set; }
        public Nullable<int> FILING_EXEMPT_ID { get; set; }
        public Nullable<int> BALLOT_POSITION { get; set; }
        public string CAND_GENDER { get; set; }
        public string R_RECORD_CREATED { get; set; }
        public string BALLOT_NAME_1 { get; set; }
        public string BALLOT_NAME_2 { get; set; }
        public string COUNTY_PETITION_ID { get; set; }
        public Nullable<int> PET_TOT_MIN_SIGN { get; set; }
        public Nullable<System.DateTime> PET_TOT_MIN_SIGN_AS_OF_DATE { get; set; }
        public Nullable<int> PET_TOT_NUM_SIGN { get; set; }
        public string PET_STATUS { get; set; }
        public string R_FILING_EXEMPT { get; set; }
        public string R_CREATE_USER_ID { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<int> PARENT_OFF_DIST_MAP_ID { get; set; }
        public Nullable<int> ELECTION_OFFICE_ID { get; set; }
    
        public virtual ICollection<BALLOT_CORRESPONDENCE> BALLOT_CORRESPONDENCE { get; set; }
        public virtual ICollection<BANK_MAPPING> BANK_MAPPING { get; set; }
        public virtual CANDIDATE CANDIDATE { get; set; }
        public virtual ICollection<CANDIDATE_COMMITTEE> CANDIDATE_COMMITTEE { get; set; }
        public virtual ICollection<CANDIDATE_CONTACT_MAPPING> CANDIDATE_CONTACT_MAPPING { get; set; }
        public virtual ICollection<CANDIDATE_HISTORY> CANDIDATE_HISTORY { get; set; }
        public virtual COUNTY COUNTY { get; set; }
        public virtual ICollection<COURT_HEARING> COURT_HEARING { get; set; }
        public virtual ELECTION ELECTION { get; set; }
        public virtual ICollection<ELECTION_CAND_ADDR_MAPPING> ELECTION_CAND_ADDR_MAPPING { get; set; }
        public virtual ICollection<ELECTION_CAND_CONTACT_MAPPING> ELECTION_CAND_CONTACT_MAPPING { get; set; }
        public virtual ICollection<ELECTION_CAND_DOCUMENTATION> ELECTION_CAND_DOCUMENTATION { get; set; }
        public virtual ICollection<ELECTION_CAND_MAPPING> ELECTION_CAND_MAPPING { get; set; }
        public virtual ICollection<ELECTION_CAND_NAME_MAPPING> ELECTION_CAND_NAME_MAPPING { get; set; }
        public virtual ICollection<ELECTION_CAND_SIGNATURE> ELECTION_CAND_SIGNATURE { get; set; }
        public virtual MUNICIPALITY MUNICIPALITY { get; set; }
        public virtual TREASURER TREASURER { get; set; }
        public virtual ICollection<FILER_COMMENTS_MAPPING> FILER_COMMENTS_MAPPING { get; set; }
        public virtual ICollection<FILER_ELECTION_CAND_MAPPING> FILER_ELECTION_CAND_MAPPING { get; set; }
        public virtual ICollection<FILER_HOLD_HISTORY> FILER_HOLD_HISTORY { get; set; }
        public virtual ICollection<PETITION_FORM_MAPPING> PETITION_FORM_MAPPING { get; set; }
        public virtual ICollection<PETITION_FORM_MAPPING> PETITION_FORM_MAPPING1 { get; set; }
        public virtual ICollection<SBOE_RECOMMENDATIONS_DECISION> SBOE_RECOMMENDATIONS_DECISION { get; set; }
        public virtual ICollection<SUPPORTED_CANDIDATE_MAPPING> SUPPORTED_CANDIDATE_MAPPING { get; set; }
        public virtual ICollection<SUPPORTED_CANDIDATE_MAPPING> SUPPORTED_CANDIDATE_MAPPING1 { get; set; }
        public virtual ICollection<SUPPORTING_DOCUMENTS> SUPPORTING_DOCUMENTS { get; set; }
        public virtual ELECTION_OFFICE ELECTION_OFFICE { get; set; }
    }
}
