//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELECTION_TYPE
    {
        public ELECTION_TYPE()
        {
            this.CONTRIBUTION_LIMIT = new HashSet<CONTRIBUTION_LIMIT>();
            this.ELECTIONs = new HashSet<ELECTION>();
            this.ELECTION_DATA_DEFAULT = new HashSet<ELECTION_DATA_DEFAULT>();
            this.FILING_TYPE = new HashSet<FILING_TYPE>();
            this.IE_POLITICAL_COMMUNICATION = new HashSet<IE_POLITICAL_COMMUNICATION>();
            this.POLITICAL_CALENDAR_LABEL_MAP = new HashSet<POLITICAL_CALENDAR_LABEL_MAP>();
        }
    
        public int ELECT_TYPE_ID { get; set; }
        public string ELECT_TYPE_DESC { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<CONTRIBUTION_LIMIT> CONTRIBUTION_LIMIT { get; set; }
        public virtual ICollection<ELECTION> ELECTIONs { get; set; }
        public virtual ICollection<ELECTION_DATA_DEFAULT> ELECTION_DATA_DEFAULT { get; set; }
        public virtual ICollection<FILING_TYPE> FILING_TYPE { get; set; }
        public virtual ICollection<IE_POLITICAL_COMMUNICATION> IE_POLITICAL_COMMUNICATION { get; set; }
        public virtual ICollection<POLITICAL_CALENDAR_LABEL_MAP> POLITICAL_CALENDAR_LABEL_MAP { get; set; }
    }
}
