//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELECTION
    {
        public ELECTION()
        {
            this.BALLOT_PROPOSALS = new HashSet<BALLOT_PROPOSALS>();
            this.CONTRIBUTION_LIMIT_DISTRICT = new HashSet<CONTRIBUTION_LIMIT_DISTRICT>();
            this.CONTRIBUTION_LIMIT_FORMULA = new HashSet<CONTRIBUTION_LIMIT_FORMULA>();
            this.CONTRIBUTION_LIMIT_STATE = new HashSet<CONTRIBUTION_LIMIT_STATE>();
            this.PETITION_HISTORY = new HashSet<PETITION_HISTORY>();
            this.FILINGS_ENCRYPTED = new HashSet<FILINGS_ENCRYPTED>();
            this.ELECTION_CANDIDATE = new HashSet<ELECTION_CANDIDATE>();
            this.PET_ELECTION_MAPPING = new HashSet<PET_ELECTION_MAPPING>();
            this.NON_PARTICIPATION = new HashSet<NON_PARTICIPATION>();
        }
    
        public int ELECT_ID { get; set; }
        public Nullable<int> POL_CAL_DATE_ID { get; set; }
        public int ELECT_YEAR_ID { get; set; }
        public int ELECT_TYPE_ID { get; set; }
        public Nullable<int> MUNICIPALITY_ID { get; set; }
        public Nullable<int> OFFICE_TYPE_ID { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<BALLOT_PROPOSALS> BALLOT_PROPOSALS { get; set; }
        public virtual ICollection<CONTRIBUTION_LIMIT_DISTRICT> CONTRIBUTION_LIMIT_DISTRICT { get; set; }
        public virtual ICollection<CONTRIBUTION_LIMIT_FORMULA> CONTRIBUTION_LIMIT_FORMULA { get; set; }
        public virtual ICollection<CONTRIBUTION_LIMIT_STATE> CONTRIBUTION_LIMIT_STATE { get; set; }
        public virtual ICollection<PETITION_HISTORY> PETITION_HISTORY { get; set; }
        public virtual ICollection<FILINGS_ENCRYPTED> FILINGS_ENCRYPTED { get; set; }
        public virtual ELECTION_TYPE ELECTION_TYPE { get; set; }
        public virtual ELECTION_YEAR ELECTION_YEAR { get; set; }
        public virtual ICollection<ELECTION_CANDIDATE> ELECTION_CANDIDATE { get; set; }
        public virtual ICollection<PET_ELECTION_MAPPING> PET_ELECTION_MAPPING { get; set; }
        public virtual MUNICIPALITY MUNICIPALITY { get; set; }
        public virtual ICollection<NON_PARTICIPATION> NON_PARTICIPATION { get; set; }
        public virtual OFFICE_TYPE OFFICE_TYPE { get; set; }
    }
}
