//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELECTION_CANDIDATE_HISTORY
    {
        public long ELECT_CAND_HIST_ID { get; set; }
        public long CAND_ID { get; set; }
        public int OFFICE_ID { get; set; }
        public Nullable<int> MUNICIPALITY_ID { get; set; }
        public Nullable<int> COUNTY_ID { get; set; }
        public int BALLOT_ORDER_ID { get; set; }
        public int BALLOT_TYPE_ID { get; set; }
        public int ACTUAL_BALLOT_ORDER_ID { get; set; }
        public string CAND_STATUS { get; set; }
        public string INVALID_REASON { get; set; }
        public string BALLOT_FNAME { get; set; }
        public string BALLOT_MNAME { get; set; }
        public string BALLOT_LNAME { get; set; }
        public string COUNTY_PETITION_ID { get; set; }
        public Nullable<int> PET_TOT_MIN_SIGN { get; set; }
        public Nullable<System.DateTime> PET_TOT_MIN_SIGN_AS_OF_DATE { get; set; }
        public Nullable<int> PET_TOT_NUM_SIGN { get; set; }
        public string PET_STATUS { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual BALLOT_ORDER BALLOT_ORDER { get; set; }
        public virtual COUNTY COUNTY { get; set; }
        public virtual MUNICIPALITY MUNICIPALITY { get; set; }
        public virtual OFFICE OFFICE { get; set; }
    }
}
