//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELECTION_DATA_DEFAULT
    {
        public int ELECTION_DATA_DEFAULT_ID { get; set; }
        public int ELECTION_YEAR_ID { get; set; }
        public int OFFICE_TYPE_ID { get; set; }
        public int ELECT_TYPE_ID { get; set; }
        public Nullable<int> COUNTY_ID { get; set; }
        public Nullable<int> MUNICIPALITY_ID { get; set; }
        public int POL_CAL_DATE_ID { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual COUNTY COUNTY { get; set; }
        public virtual ELECTION_TYPE ELECTION_TYPE { get; set; }
        public virtual ELECTION_YEAR ELECTION_YEAR { get; set; }
        public virtual MUNICIPALITY MUNICIPALITY { get; set; }
        public virtual OFFICE_TYPE OFFICE_TYPE { get; set; }
    }
}
