//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELECTION_OFFICE
    {
        public ELECTION_OFFICE()
        {
            this.ELECTION_CANDIDATE = new HashSet<ELECTION_CANDIDATE>();
        }
    
        public int ELECTION_OFFICE_ID { get; set; }
        public int ELECT_ID { get; set; }
        public int OFF_DIST_MAP_ID { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<int> PARENT_OFF_DIST_MAP_ID { get; set; }
        public Nullable<int> PARTY_ELECT_ID { get; set; }
        public Nullable<int> VOTE_FOR { get; set; }
        public Nullable<int> MUNICIPALITY_ID { get; set; }
    
        public virtual ICollection<ELECTION_CANDIDATE> ELECTION_CANDIDATE { get; set; }
        public virtual MUNICIPALITY MUNICIPALITY { get; set; }
        public virtual OFFICE_DISTRICT_MAPPING OFFICE_DISTRICT_MAPPING { get; set; }
        public virtual PARTY_ELECTION PARTY_ELECTION { get; set; }
    }
}
