//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELECTION_CAND_MAPPING
    {
        public ELECTION_CAND_MAPPING()
        {
            this.PETITION_RTD_FORMS_DUE_DATES = new HashSet<PETITION_RTD_FORMS_DUE_DATES>();
        }
    
        public long ELECTION_CAND_MAPPING_ID { get; set; }
        public long ELECT_CAND_ID { get; set; }
        public Nullable<long> PET_ID { get; set; }
        public Nullable<int> PET_FRM_MAP_ID { get; set; }
        public Nullable<int> PARTY_ELECT_ID { get; set; }
        public string CAND_STATUS { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string R_WINNER { get; set; }
        public Nullable<System.DateTime> WINNER_CERT_DATE { get; set; }
        public string R_UNCONTESTED { get; set; }
        public string BALLOT_NAME_1 { get; set; }
        public string BALLOT_NAME_2 { get; set; }
        public string COUNTY_PETITION_ID { get; set; }
        public Nullable<int> PET_TOT_MIN_SIGN { get; set; }
        public Nullable<System.DateTime> PET_TOT_MIN_SIGN_AS_OF_DATE { get; set; }
        public Nullable<int> PET_TOT_NUM_SIGN { get; set; }
        public string PET_STATUS { get; set; }
        public Nullable<int> BALLOT_POSITION { get; set; }
        public Nullable<int> BALLOT_TYPE_ID { get; set; }
        public string SUPPORTED_FIRST_NAME { get; set; }
        public string SUPPORTED_MIDDLE_NAME { get; set; }
        public string SUPPORTED_LAST_NAME { get; set; }
        public string SUPPORTED_SUFFIX { get; set; }
    
        public virtual ELECTION_CANDIDATE ELECTION_CANDIDATE { get; set; }
        public virtual PARTY_ELECTION PARTY_ELECTION { get; set; }
        public virtual PETITION PETITION { get; set; }
        public virtual PETITION_FORM_MAPPING PETITION_FORM_MAPPING { get; set; }
        public virtual ICollection<PETITION_RTD_FORMS_DUE_DATES> PETITION_RTD_FORMS_DUE_DATES { get; set; }
    }
}
