//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELECTION_YEAR
    {
        public ELECTION_YEAR()
        {
            this.CONTRIBUTION_LIMIT = new HashSet<CONTRIBUTION_LIMIT>();
            this.ELECTIONs = new HashSet<ELECTION>();
            this.ELECTION_DATA_DEFAULT = new HashSet<ELECTION_DATA_DEFAULT>();
            this.ENROLLMENTs = new HashSet<ENROLLMENT>();
            this.FILING_PERIOD = new HashSet<FILING_PERIOD>();
            this.FILER_CONVERSION_MAPPING = new HashSet<FILER_CONVERSION_MAPPING>();
            this.POLITICAL_CALENDAR_DATES = new HashSet<POLITICAL_CALENDAR_DATES>();
            this.PARTY_ELECTION_HISTORY1 = new HashSet<PARTY_ELECTION_HISTORY>();
            this.IE_POLITICAL_COMMUNICATION = new HashSet<IE_POLITICAL_COMMUNICATION>();
            this.OFFICE_TERM_MAPPING = new HashSet<OFFICE_TERM_MAPPING>();
            this.PARTY_CALL = new HashSet<PARTY_CALL>();
        }
    
        public int ELECTION_YEAR_ID { get; set; }
        public int ELECT_YEAR { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<CONTRIBUTION_LIMIT> CONTRIBUTION_LIMIT { get; set; }
        public virtual ICollection<ELECTION> ELECTIONs { get; set; }
        public virtual ICollection<ELECTION_DATA_DEFAULT> ELECTION_DATA_DEFAULT { get; set; }
        public virtual PARTY_ELECTION_HISTORY PARTY_ELECTION_HISTORY { get; set; }
        public virtual ICollection<ENROLLMENT> ENROLLMENTs { get; set; }
        public virtual ICollection<FILING_PERIOD> FILING_PERIOD { get; set; }
        public virtual ICollection<FILER_CONVERSION_MAPPING> FILER_CONVERSION_MAPPING { get; set; }
        public virtual ICollection<POLITICAL_CALENDAR_DATES> POLITICAL_CALENDAR_DATES { get; set; }
        public virtual ICollection<PARTY_ELECTION_HISTORY> PARTY_ELECTION_HISTORY1 { get; set; }
        public virtual ICollection<IE_POLITICAL_COMMUNICATION> IE_POLITICAL_COMMUNICATION { get; set; }
        public virtual ICollection<OFFICE_TERM_MAPPING> OFFICE_TERM_MAPPING { get; set; }
        public virtual ICollection<PARTY_CALL> PARTY_CALL { get; set; }
    }
}
