//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public EMPLOYEE()
        {
            this.COMPLIANCE_REVIEW = new HashSet<COMPLIANCE_REVIEW>();
            this.TERMINATION_REVIEW = new HashSet<TERMINATION_REVIEW>();
            this.EMPLOYEE_ROLE_MAPPING = new HashSet<EMPLOYEE_ROLE_MAPPING>();
            this.EXECUTIVE_REVIEWER = new HashSet<EXECUTIVE_REVIEWER>();
            this.FILING_EXEMPTION_REVIEW = new HashSet<FILING_EXEMPTION_REVIEW>();
        }
    
        public int EMP_ID { get; set; }
        public int UNIT_ID { get; set; }
        public string EMP_USERID { get; set; }
        public string EMP_ITEM_NUMBER { get; set; }
        public string EMP_FIRST_NAME { get; set; }
        public string EMP_LAST_NAME { get; set; }
        public string EMP_MIDDLE_NAME { get; set; }
        public string EMP_SUFFIX { get; set; }
        public string EMP_PREFIX { get; set; }
        public string EMP_TITLE { get; set; }
        public string EMP_ADDR_STR_NUM { get; set; }
        public string EMP_ADDR_STR_NAME { get; set; }
        public string EMP_ADDR_ADDR1 { get; set; }
        public string EMP_ADDR_ADDR2 { get; set; }
        public string EMP_ADDR_CITY { get; set; }
        public string EMP_ADDR_STATE { get; set; }
        public string EMP_ADDR_ZIP { get; set; }
        public string EMP_ADDR_ZIP4 { get; set; }
        public string EMP_INTERNAL_PHONE { get; set; }
        public string EMP_EMAIL_WORK { get; set; }
        public string EMP_PUBLIC_PHONE { get; set; }
        public string EMP_PERSONAL_CONTACT { get; set; }
        public string EMP_EMERGENCY_CONTACT { get; set; }
        public string EMP_EMERGENCY_CONTACT_RELATION { get; set; }
        public string EMP_EMERGENCY_CONTACT_CELL { get; set; }
        public string EMP_EMERGENCY_CONTACT_NUMBER { get; set; }
        public string EMP_EMERGENCY_CONTACT_HOME_NUM { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<COMPLIANCE_REVIEW> COMPLIANCE_REVIEW { get; set; }
        public virtual ICollection<TERMINATION_REVIEW> TERMINATION_REVIEW { get; set; }
        public virtual ICollection<EMPLOYEE_ROLE_MAPPING> EMPLOYEE_ROLE_MAPPING { get; set; }
        public virtual ICollection<EXECUTIVE_REVIEWER> EXECUTIVE_REVIEWER { get; set; }
        public virtual ICollection<FILING_EXEMPTION_REVIEW> FILING_EXEMPTION_REVIEW { get; set; }
        public virtual UNIT UNIT { get; set; }
    }
}
