//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENROLLMENT
    {
        public int ENROLL_ID { get; set; }
        public int COUNTY_ID { get; set; }
        public int DIST_MAP_ID { get; set; }
        public int ELECT_YEAR_ID { get; set; }
        public int MASTER_TYPE_ID { get; set; }
        public string REG_TOWN_CITY { get; set; }
        public string REG_PRECINCT_CODE { get; set; }
        public int ENROLL_TOTALS { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual COUNTY COUNTY { get; set; }
        public virtual ELECTION_YEAR ELECTION_YEAR { get; set; }
        public virtual MASTER_TYPE MASTER_TYPE { get; set; }
    }
}
