//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERROR_LOG_7122021
    {
        public int ERROR_LOG_ID { get; set; }
        public int APPLICATION_ID { get; set; }
        public string ERROR_MESSAGE { get; set; }
        public string OPERATION_CLASS { get; set; }
        public string FUNCTION_METHOD { get; set; }
        public string REQUEST_MESSAGE { get; set; }
        public string RESPONSE_MESSAGE { get; set; }
        public string DISPLAY_MESSAGE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
    }
}
