//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESCROW_TRANSACTIONS
    {
        public int ESCROW_TRANS_ID { get; set; }
        public int ESCROW_ID { get; set; }
        public Nullable<int> ESCROW_PROD_ID { get; set; }
        public Nullable<long> COMMENT_ID { get; set; }
        public string ESCROW_TRANS_TYPE { get; set; }
        public string ESCROW_CHECK_NUM { get; set; }
        public Nullable<int> ESCROW_PROD_QTY { get; set; }
        public string ESCROW_PROD_COST { get; set; }
        public string ESCROW_CREDIT_AMT { get; set; }
        public string ESCROW_DEBIT_AMT { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual COMMENT COMMENT { get; set; }
        public virtual ESCROW ESCROW { get; set; }
        public virtual ESCROW_PRODUCT ESCROW_PRODUCT { get; set; }
    }
}
