//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESCROW_PRODUCT
    {
        public ESCROW_PRODUCT()
        {
            this.ESCROW_TRANSACTIONS = new HashSet<ESCROW_TRANSACTIONS>();
        }
    
        public int ESCROW_PROD_ID { get; set; }
        public int SBOE_UNIT_ID { get; set; }
        public string ESCROW_PROD_NAME { get; set; }
        public string ESCROW_PROD_DESC { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<ESCROW_TRANSACTIONS> ESCROW_TRANSACTIONS { get; set; }
        public virtual SBOE_UNIT SBOE_UNIT { get; set; }
    }
}
