//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESCROW
    {
        public ESCROW()
        {
            this.ESCROW_AUTHORIZED_USER = new HashSet<ESCROW_AUTHORIZED_USER>();
            this.ESCROW_TRANSACTIONS = new HashSet<ESCROW_TRANSACTIONS>();
        }
    
        public int ESCROW_ID { get; set; }
        public long ADDR_ID { get; set; }
        public Nullable<long> CAND_ID { get; set; }
        public string ORG_NAME { get; set; }
        public int FED_SS_ID { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ADDRESS ADDRESS { get; set; }
        public virtual ICollection<ESCROW_AUTHORIZED_USER> ESCROW_AUTHORIZED_USER { get; set; }
        public virtual ICollection<ESCROW_TRANSACTIONS> ESCROW_TRANSACTIONS { get; set; }
    }
}
