//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXECUTIVE_REVIEWER
    {
        public EXECUTIVE_REVIEWER()
        {
            this.PETITION_REVIEW = new HashSet<PETITION_REVIEW>();
        }
    
        public int EXE_REV_ID { get; set; }
        public int EMP_ID { get; set; }
        public int ROLE_ID { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual ICollection<PETITION_REVIEW> PETITION_REVIEW { get; set; }
    }
}
