//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILER_CONVERSION_MAPPING
    {
        public int FILER_CONV_MAP_ID { get; set; }
        public Nullable<long> CAND_ID { get; set; }
        public Nullable<long> COMM_ID { get; set; }
        public Nullable<long> TREAS_ID { get; set; }
        public Nullable<int> ELECT_YEAR_ID { get; set; }
        public string FILER_PREVIOUS_ID { get; set; }
        public string FILER_PIN { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual COMMITTEE COMMITTEE { get; set; }
        public virtual ELECTION_YEAR ELECTION_YEAR { get; set; }
        public virtual TREASURER TREASURER { get; set; }
    }
}
