//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILER_SCAN_MAPPING
    {
        public int COMM_SCAN_MAP_ID { get; set; }
        public Nullable<long> CAND_COMM_ID { get; set; }
        public long SCAN_DOC_ID { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual CANDIDATE_COMMITTEE CANDIDATE_COMMITTEE { get; set; }
        public virtual SCAN_DOCUMENT SCAN_DOCUMENT { get; set; }
    }
}
