//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILER_HOLD_TYPE
    {
        public FILER_HOLD_TYPE()
        {
            this.FILER_HOLD_HISTORY = new HashSet<FILER_HOLD_HISTORY>();
        }
    
        public int FILER_HOLD_TYPE_ID { get; set; }
        public string FILER_HOLD_TYPE_DESC { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<FILER_HOLD_HISTORY> FILER_HOLD_HISTORY { get; set; }
    }
}
