//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILER_HOLD_HISTORY
    {
        public int FILER_HOLD_HISTORY_ID { get; set; }
        public long FILER_ID { get; set; }
        public Nullable<long> ELECT_CAND_ID { get; set; }
        public Nullable<long> COMM_ID { get; set; }
        public Nullable<int> FILER_HOLD_TYPE_ID { get; set; }
        public Nullable<System.DateTime> FILER_HOLD_FROM_DATE { get; set; }
        public Nullable<System.DateTime> FILER_HOLD_TO_DATE { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<int> FORM_ID { get; set; }
    
        public virtual COMMITTEE COMMITTEE { get; set; }
        public virtual ELECTION_CANDIDATE ELECTION_CANDIDATE { get; set; }
        public virtual FILER_HOLD_TYPE FILER_HOLD_TYPE { get; set; }
        public virtual FORM FORM { get; set; }
    }
}
