//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILER_PURPOSE
    {
        public FILER_PURPOSE()
        {
            this.COMM_OPERATIONAL_INDIVIDUAL = new HashSet<COMM_OPERATIONAL_INDIVIDUAL>();
            this.COMM_OPERATIONAL_INDIVIDUAL1 = new HashSet<COMM_OPERATIONAL_INDIVIDUAL>();
            this.COMM_OPERATIONAL_INDIVIDUAL2 = new HashSet<COMM_OPERATIONAL_INDIVIDUAL>();
        }
    
        public int FILER_PURP_ID { get; set; }
        public string SHORT_DEFINITION { get; set; }
        public string LONG_DEFINITION { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<COMM_OPERATIONAL_INDIVIDUAL> COMM_OPERATIONAL_INDIVIDUAL { get; set; }
        public virtual ICollection<COMM_OPERATIONAL_INDIVIDUAL> COMM_OPERATIONAL_INDIVIDUAL1 { get; set; }
        public virtual ICollection<COMM_OPERATIONAL_INDIVIDUAL> COMM_OPERATIONAL_INDIVIDUAL2 { get; set; }
    }
}
