//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILINGS_ENCRYPTED
    {
        public long FILINGS_ENC_ID { get; set; }
        public Nullable<int> FILING_PERIOD_ID { get; set; }
        public long FILER_ID { get; set; }
        public Nullable<int> FILING_CAT_ID { get; set; }
        public Nullable<int> ELECT_ID { get; set; }
        public string FILING_MEDIA { get; set; }
        public string FILINGS_SOURCE { get; set; }
        public string R_CAMP_MATERIAL { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ELECTION ELECTION { get; set; }
        public virtual FILING_CATEGORY FILING_CATEGORY { get; set; }
    }
}
