//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILING_METHOD
    {
        public FILING_METHOD()
        {
            this.CAMPAIGN_MATERIAL = new HashSet<CAMPAIGN_MATERIAL>();
            this.SUPPORTING_DOCUMENTS = new HashSet<SUPPORTING_DOCUMENTS>();
        }
    
        public int FILING_METHOD_ID { get; set; }
        public string FILING_METHOD_DESC { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<CAMPAIGN_MATERIAL> CAMPAIGN_MATERIAL { get; set; }
        public virtual ICollection<SUPPORTING_DOCUMENTS> SUPPORTING_DOCUMENTS { get; set; }
    }
}
