//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILING_EXEMPTION_DETAILS
    {
        public FILING_EXEMPTION_DETAILS()
        {
            this.FILING_EXEMPTION_REVIEW = new HashSet<FILING_EXEMPTION_REVIEW>();
        }
    
        public int FILING_EXEMPT_DET_ID { get; set; }
        public int FILING_EXEMPT_ID { get; set; }
        public long FILER_ID { get; set; }
        public Nullable<long> COMMENT_ID { get; set; }
        public int MASTER_TYPE_ID { get; set; }
        public Nullable<System.DateTime> FILING_EXEMPT_FROM { get; set; }
        public Nullable<System.DateTime> FILING_EXEMPT_TO { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual COMMENT COMMENT { get; set; }
        public virtual FILING_EXEMPTION FILING_EXEMPTION { get; set; }
        public virtual ICollection<FILING_EXEMPTION_REVIEW> FILING_EXEMPTION_REVIEW { get; set; }
        public virtual MASTER_TYPE MASTER_TYPE { get; set; }
    }
}
