//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILING_EXEMPTION
    {
        public FILING_EXEMPTION()
        {
            this.FILING_EXEMPTION_DETAILS = new HashSet<FILING_EXEMPTION_DETAILS>();
        }
    
        public int FILING_EXEMPT_ID { get; set; }
        public int FORM_ID { get; set; }
        public string FILING_EXEMPT_DESC { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<FILING_EXEMPTION_DETAILS> FILING_EXEMPTION_DETAILS { get; set; }
        public virtual FORM FORM { get; set; }
    }
}
