//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILING_EXEMPTION_REVIEW
    {
        public int FILING_EXEMPT_REVIEW_ID { get; set; }
        public int FILING_EXEMPT_DET_ID { get; set; }
        public int EMP_ID { get; set; }
        public Nullable<long> COMMENT_ID { get; set; }
        public string R_ALL_REPORTS_RECEIVED { get; set; }
        public string R_NO_NEGATIVE_BALANCE { get; set; }
        public string R_ZERO_ENDING_BALANCE { get; set; }
        public string R_OUTSTANDING_LOANS { get; set; }
        public string R_LOANS_FORGIVEN { get; set; }
        public string R_LETTER_FORGIVENESS_FILED { get; set; }
        public string R_FORMS_FILED { get; set; }
        public string R_REPORT_RECEIVED { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual COMMENT COMMENT { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual FILING_EXEMPTION_DETAILS FILING_EXEMPTION_DETAILS { get; set; }
    }
}
