//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILING_CATEGORY
    {
        public FILING_CATEGORY()
        {
            this.FILER_STATEMENT = new HashSet<FILER_STATEMENT>();
            this.FILING_CATEGORY_COMM_MAPPING = new HashSet<FILING_CATEGORY_COMM_MAPPING>();
            this.FILINGS_ENCRYPTED = new HashSet<FILINGS_ENCRYPTED>();
        }
    
        public int FILING_CAT_ID { get; set; }
        public string FILING_CAT_DESC { get; set; }
        public string FILING_CAT_SUBTYPE { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<FILER_STATEMENT> FILER_STATEMENT { get; set; }
        public virtual ICollection<FILING_CATEGORY_COMM_MAPPING> FILING_CATEGORY_COMM_MAPPING { get; set; }
        public virtual ICollection<FILINGS_ENCRYPTED> FILINGS_ENCRYPTED { get; set; }
    }
}
