//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILING
    {
        public FILING()
        {
            this.CAMPAIGN_MATERIAL = new HashSet<CAMPAIGN_MATERIAL>();
            this.EFS_VENDOR_IMPORT = new HashSet<EFS_VENDOR_IMPORT>();
        }
    
        public long FILINGS_ID { get; set; }
        public Nullable<int> FILING_PERIOD_ID { get; set; }
        public long FILER_ID { get; set; }
        public Nullable<int> FILING_CAT_ID { get; set; }
        public Nullable<int> ELECT_ID { get; set; }
        public Nullable<int> RESIG_TERM_TYPE_ID { get; set; }
        public string FILING_MEDIA { get; set; }
        public string FILINGS_SOURCE { get; set; }
        public string R_CAMP_MATERIAL { get; set; }
        public Nullable<int> FILINGS_VERSION { get; set; }
        public Nullable<long> FILINGS_ORIG_FILINGS_ID { get; set; }
        public string R_STATUS { get; set; }
        public Nullable<System.DateTime> R_FILING_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<System.DateTime> R_DATE { get; set; }
    
        public virtual ICollection<CAMPAIGN_MATERIAL> CAMPAIGN_MATERIAL { get; set; }
        public virtual ICollection<EFS_VENDOR_IMPORT> EFS_VENDOR_IMPORT { get; set; }
        public virtual RESIGNATION_TERMINATION_TYPE RESIGNATION_TERMINATION_TYPE { get; set; }
    }
}
