//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILING_SCHEDULES
    {
        public FILING_SCHEDULES()
        {
            this.COMPLIANCE_REVIEW_DETAILS = new HashSet<COMPLIANCE_REVIEW_DETAILS>();
            this.FILING_SCHEDULE_COMM_MAPPING = new HashSet<FILING_SCHEDULE_COMM_MAPPING>();
            this.PURPOSE_CODE_SCHEDULE_MAPPING = new HashSet<PURPOSE_CODE_SCHEDULE_MAPPING>();
            this.FILING_TRANSACTIONS_ENCRYPTED = new HashSet<FILING_TRANSACTIONS_ENCRYPTED>();
            this.FILING_TRANSACTIONS_HISTORY = new HashSet<FILING_TRANSACTIONS_HISTORY>();
        }
    
        public int FILING_SCHED_ID { get; set; }
        public string FILING_SCHED_ABBREV { get; set; }
        public string FILING_SCHED_DESC { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<COMPLIANCE_REVIEW_DETAILS> COMPLIANCE_REVIEW_DETAILS { get; set; }
        public virtual ICollection<FILING_SCHEDULE_COMM_MAPPING> FILING_SCHEDULE_COMM_MAPPING { get; set; }
        public virtual ICollection<PURPOSE_CODE_SCHEDULE_MAPPING> PURPOSE_CODE_SCHEDULE_MAPPING { get; set; }
        public virtual ICollection<FILING_TRANSACTIONS_ENCRYPTED> FILING_TRANSACTIONS_ENCRYPTED { get; set; }
        public virtual ICollection<FILING_TRANSACTIONS_HISTORY> FILING_TRANSACTIONS_HISTORY { get; set; }
    }
}
