//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILING_ENTITY
    {
        public FILING_ENTITY()
        {
            this.FILING_TRANSACTIONS_ENCRYPTED = new HashSet<FILING_TRANSACTIONS_ENCRYPTED>();
            this.FILING_TRANSACTIONS_HISTORY = new HashSet<FILING_TRANSACTIONS_HISTORY>();
        }
    
        public long FLNG_ENT_ID { get; set; }
        public string FLNG_ENT_NAME { get; set; }
        public string FLNG_ENT_EIN_SSN { get; set; }
        public string FLNG_ENT_FIRST_NAME { get; set; }
        public string FLNG_ENT_MIDDLE_NAME { get; set; }
        public string FLNG_ENT_LAST_NAME { get; set; }
        public string FLNG_ENT_STR_NUM { get; set; }
        public string FLNG_ENT_STR_NAME { get; set; }
        public string FLNG_ENT_ADDR1 { get; set; }
        public string FLNG_ENT_ADDR2 { get; set; }
        public string FLNG_ENT_CITY { get; set; }
        public string FLNG_ENT_STATE { get; set; }
        public string FLNG_ENT_ZIP { get; set; }
        public string FLNG_ENT_COUNTRY { get; set; }
        public string FLNG_ENT_OCCUPATION { get; set; }
        public string FLNG_ENT_EMPLOYER { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<FILING_TRANSACTIONS_ENCRYPTED> FILING_TRANSACTIONS_ENCRYPTED { get; set; }
        public virtual ICollection<FILING_TRANSACTIONS_HISTORY> FILING_TRANSACTIONS_HISTORY { get; set; }
    }
}
