//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILING_TRANSACTIONS_HISTORY
    {
        public long FILING_TRANS_HIST_ID { get; set; }
        public Nullable<long> FLNG_ENT_ID { get; set; }
        public long FILINGS_ID { get; set; }
        public Nullable<int> FILING_SCHED_ID { get; set; }
        public int CNTRBR_TYPE_ID { get; set; }
        public int CNTRBN_TYPE_ID { get; set; }
        public Nullable<int> PAYMENT_TYPE_ID { get; set; }
        public int RECEIPT_TYPE_ID { get; set; }
        public int PURPOSE_CODE_ID { get; set; }
        public int TRANSFER_TYPE_ID { get; set; }
        public Nullable<int> TRANS_CODE { get; set; }
        public Nullable<System.DateTime> SCHED_DATE { get; set; }
        public System.DateTime ORG_DATE { get; set; }
        public System.DateTime PAY_DATE { get; set; }
        public string PAY_NUMBER { get; set; }
        public Nullable<int> ORG_AMT { get; set; }
        public int OWED_AMT { get; set; }
        public string TRANS_DESC { get; set; }
        public string TRANS_EXPLNTN { get; set; }
        public Nullable<System.DateTime> ELECTION_DATE { get; set; }
        public string ELECTION_TYPE { get; set; }
        public string ELECTION_YEAR { get; set; }
        public string DIST_OFF_CAND_BAL_PROP { get; set; }
        public string R_BANK_LOAN { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual CONTRIBUTION_TYPE CONTRIBUTION_TYPE { get; set; }
        public virtual CONTRIBUTOR_TYPE CONTRIBUTOR_TYPE { get; set; }
        public virtual FILING_ENTITY FILING_ENTITY { get; set; }
        public virtual FILING_SCHEDULES FILING_SCHEDULES { get; set; }
        public virtual PAYMENT_TYPE PAYMENT_TYPE { get; set; }
        public virtual RECEIPT_TYPE RECEIPT_TYPE { get; set; }
        public virtual TRANSFER_TYPE TRANSFER_TYPE { get; set; }
    }
}
