//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILING_TRANSACTIONS_IMPORT
    {
        public long FILING_TRANS_ID { get; set; }
        public Nullable<long> FLNG_ENT_ID { get; set; }
        public string LOAN_LIB_NUMBER { get; set; }
        public string TRANS_NUMBER { get; set; }
        public string TRANS_MAPPING { get; set; }
        public long FILINGS_ID { get; set; }
        public Nullable<int> FILING_SCHED_ID { get; set; }
        public Nullable<int> CNTRBR_TYPE_ID { get; set; }
        public Nullable<int> CNTRBN_TYPE_ID { get; set; }
        public Nullable<int> PAYMENT_TYPE_ID { get; set; }
        public Nullable<int> RECEIPT_TYPE_ID { get; set; }
        public Nullable<int> PURPOSE_CODE_ID { get; set; }
        public Nullable<int> TRANSFER_TYPE_ID { get; set; }
        public Nullable<int> RECEIPT_CODE_ID { get; set; }
        public Nullable<int> LOAN_OTHER_ID { get; set; }
        public Nullable<int> TRANS_CODE { get; set; }
        public Nullable<int> MUNICIPALITY_ID { get; set; }
        public Nullable<long> TREAS_ID { get; set; }
        public Nullable<long> ADDR_ID { get; set; }
        public Nullable<long> PART_FLNG_ENT_ID { get; set; }
        public Nullable<int> OFFICE_ID { get; set; }
        public string DISTRICT { get; set; }
        public Nullable<System.DateTime> SCHED_DATE { get; set; }
        public Nullable<System.DateTime> ORG_DATE { get; set; }
        public Nullable<System.DateTime> PAY_DATE { get; set; }
        public string PAY_NUMBER { get; set; }
        public Nullable<double> ORG_AMT { get; set; }
        public Nullable<double> OWED_AMT { get; set; }
        public string TRANS_DESC { get; set; }
        public string TRANS_EXPLNTN { get; set; }
        public Nullable<System.DateTime> ELECTION_DATE { get; set; }
        public string ELECTION_TYPE { get; set; }
        public string ELECTION_YEAR { get; set; }
        public string R_BANK_LOAN { get; set; }
        public string DIST_OFF_CAND_BAL_PROP { get; set; }
        public string IE_CNTRBR_OCC { get; set; }
        public string IE_CNTRBR_EMP { get; set; }
        public string IE_DESC { get; set; }
        public string TREAS_OCCUPATION { get; set; }
        public string TREAS_EMPLOYER { get; set; }
        public string EXISTS_LIAB_TRANS_NUMBER { get; set; }
        public string R_IE_SUPPORTED { get; set; }
        public Nullable<System.DateTime> SUBMIT_DATE { get; set; }
        public string R_SUBCONTRACTOR { get; set; }
        public string R_LIABILITY { get; set; }
        public string R_ITEMIZED { get; set; }
        public string R_IE_INCLUDED { get; set; }
        public string R_STATUS { get; set; }
        public string R_AMEND { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string R_PARENT { get; set; }
        public string R_CLAIM { get; set; }
        public string R_IN_DISTRICT { get; set; }
        public string R_MINOR { get; set; }
        public string R_VENDOR { get; set; }
        public string R_LOBBYIST { get; set; }
        public string R_CONTRIBUTIONS { get; set; }
        public string R_WEEKLY { get; set; }
        public string R_SUPPORT_OPPOSE { get; set; }
    }
}
