//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HEARING
    {
        public HEARING()
        {
            this.PETITION_REVIEW = new HashSet<PETITION_REVIEW>();
        }
    
        public int HEARING_ID { get; set; }
        public int OBJ_ID { get; set; }
        public System.DateTime HEARING_DATE { get; set; }
        public System.TimeSpan HEARING_TIME { get; set; }
        public int HEARING_OFFICER_EMP_ID { get; set; }
        public Nullable<long> COMMENT_ID { get; set; }
        public int CLERK_EMP_ID { get; set; }
        public Nullable<long> TOTAL_CLAIMED_SIGNATURES { get; set; }
        public long VALID_SIGNATURE_NUM { get; set; }
        public long INVALID_SIGNATURE_NUM { get; set; }
        public string HEARING_STATUS { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual COMMENT COMMENT { get; set; }
        public virtual HEARING HEARING1 { get; set; }
        public virtual HEARING HEARING2 { get; set; }
        public virtual ICollection<PETITION_REVIEW> PETITION_REVIEW { get; set; }
        public virtual OBJECTION OBJECTION { get; set; }
    }
}
