//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IE_COMMUNICATION_FILE
    {
        public int IE_COMM_FILE_ID { get; set; }
        public int IE_POL_COMM_ID { get; set; }
        public int COMM_TYPE_ID { get; set; }
        public string IE_DESCRIPTION { get; set; }
        public string IE_COMM_DISPLAY_NAME { get; set; }
        public string IE_COMM_DOC_ID { get; set; }
        public string IE_COMM_FILENAME { get; set; }
        public string IE_FILE_EXTENSION { get; set; }
        public string IE_FILE_SIZE { get; set; }
        public Nullable<System.DateTime> IE_DATE_SUBMITTED { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual COMMUNICATION_TYPE COMMUNICATION_TYPE { get; set; }
        public virtual IE_POLITICAL_COMMUNICATION IE_POLITICAL_COMMUNICATION { get; set; }
    }
}
