//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IE_COMMITTEES
    {
        public IE_COMMITTEES()
        {
            this.IE_POLITICAL_COMMUNICATION = new HashSet<IE_POLITICAL_COMMUNICATION>();
            this.IE_REGISTRATION_INFO = new HashSet<IE_REGISTRATION_INFO>();
        }
    
        public int IE_COMM_ID { get; set; }
        public string IE_FILER_ID { get; set; }
        public string IE_COMMITTEE_NAME { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<IE_POLITICAL_COMMUNICATION> IE_POLITICAL_COMMUNICATION { get; set; }
        public virtual ICollection<IE_REGISTRATION_INFO> IE_REGISTRATION_INFO { get; set; }
    }
}
