//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IE_COMM_SUPPORT_OPPOSE
    {
        public long IE_COMM_SUPP_OPP_ID { get; set; }
        public long COMM_ID { get; set; }
        public Nullable<int> ELECTION_YEAR { get; set; }
        public Nullable<int> OFFICE_TYPE_ID { get; set; }
        public Nullable<int> OFFICE_ID { get; set; }
        public Nullable<int> OFF_DIST_MAP_ID { get; set; }
        public Nullable<int> COMM_PURPOSE_TYPE_ID { get; set; }
        public string CAND_FIRST_NAME { get; set; }
        public string CAND_MIDDLE_NAME { get; set; }
        public string CAND_LAST_NAME { get; set; }
        public string CAND_SUFFIX { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual COMM_PURPOSE_TYPE COMM_PURPOSE_TYPE { get; set; }
        public virtual COMMITTEE COMMITTEE { get; set; }
        public virtual OFFICE OFFICE { get; set; }
        public virtual OFFICE_DISTRICT_MAPPING OFFICE_DISTRICT_MAPPING { get; set; }
        public virtual OFFICE_TYPE OFFICE_TYPE { get; set; }
    }
}
