//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IE_POLITICAL_COMMUNICATION
    {
        public IE_POLITICAL_COMMUNICATION()
        {
            this.IE_COMMUNICATION_FILE = new HashSet<IE_COMMUNICATION_FILE>();
        }
    
        public int IE_POL_COMM_ID { get; set; }
        public int IE_COMM_ID { get; set; }
        public int IE_YEAR { get; set; }
        public int IE_OFFICE_TYPE { get; set; }
        public Nullable<int> COUNTY_ID { get; set; }
        public Nullable<int> MUNICIPALITY_ID { get; set; }
        public int IE_ELECTION_TYPE { get; set; }
        public System.DateTime IE_DATE_PAID { get; set; }
        public double IE_AMOUNT { get; set; }
        public string IE_RECIPIENT_NAME { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ELECTION_TYPE ELECTION_TYPE { get; set; }
        public virtual ELECTION_YEAR ELECTION_YEAR { get; set; }
        public virtual IE_COMMITTEES IE_COMMITTEES { get; set; }
        public virtual ICollection<IE_COMMUNICATION_FILE> IE_COMMUNICATION_FILE { get; set; }
        public virtual OFFICE_TYPE OFFICE_TYPE { get; set; }
    }
}
