//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IE_REGISTRATION_INFO
    {
        public int IE_REG_INFO_ID { get; set; }
        public int IE_COMM_ID { get; set; }
        public System.DateTime IE_DATE_UPLOAD { get; set; }
        public string REG_INFO_NAME { get; set; }
        public string REG_INFO_DOC_ID { get; set; }
        public string REG_INFO_FILE_NAME { get; set; }
        public string REG_FILE_EXTENSION { get; set; }
        public string REG_FILE_SIZE { get; set; }
        public string COMM_URL_NAME { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual IE_COMMITTEES IE_COMMITTEES { get; set; }
    }
}
