//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_LOOKUP
    {
        public MASTER_LOOKUP()
        {
            this.MASTER_TYPE = new HashSet<MASTER_TYPE>();
        }
    
        public int MASTER_LOOKUP_ID { get; set; }
        public string MASTER_LOOKUP_TYPE { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<MASTER_TYPE> MASTER_TYPE { get; set; }
    }
}
