//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_TYPE
    {
        public MASTER_TYPE()
        {
            this.CANDIDATE_COMMITTEE = new HashSet<CANDIDATE_COMMITTEE>();
            this.CANDIDATE_HISTORY = new HashSet<CANDIDATE_HISTORY>();
            this.COMMITTEEs = new HashSet<COMMITTEE>();
            this.COMMITTEE_HISTORY = new HashSet<COMMITTEE_HISTORY>();
            this.COMPLIANCE_REVIEW_TYPES = new HashSet<COMPLIANCE_REVIEW_TYPES>();
            this.CONTRIBUTION_LIMIT_DISTRICT = new HashSet<CONTRIBUTION_LIMIT_DISTRICT>();
            this.CONTRIBUTION_LIMIT_FORMULA = new HashSet<CONTRIBUTION_LIMIT_FORMULA>();
            this.CONTRIBUTION_LIMIT_STATE = new HashSet<CONTRIBUTION_LIMIT_STATE>();
            this.ENROLLMENTs = new HashSet<ENROLLMENT>();
            this.ENROLLMENT_COUNTY = new HashSet<ENROLLMENT_COUNTY>();
            this.ENROLLMENT_DISTRICT = new HashSet<ENROLLMENT_DISTRICT>();
            this.ENROLLMENT_ED = new HashSet<ENROLLMENT_ED>();
            this.FILING_EXEMPTION_DETAILS = new HashSet<FILING_EXEMPTION_DETAILS>();
            this.REVIEW_TYPES = new HashSet<REVIEW_TYPES>();
            this.TREASURERs = new HashSet<TREASURER>();
            this.TREASURER_HISTORY = new HashSet<TREASURER_HISTORY>();
        }
    
        public int MASTER_TYPE_ID { get; set; }
        public int MASTER_LOOKUP_ID { get; set; }
        public string MASTER_TYPE_DESC { get; set; }
        public string MASTER_TYPE_ABBREV { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<CANDIDATE_COMMITTEE> CANDIDATE_COMMITTEE { get; set; }
        public virtual ICollection<CANDIDATE_HISTORY> CANDIDATE_HISTORY { get; set; }
        public virtual ICollection<COMMITTEE> COMMITTEEs { get; set; }
        public virtual ICollection<COMMITTEE_HISTORY> COMMITTEE_HISTORY { get; set; }
        public virtual ICollection<COMPLIANCE_REVIEW_TYPES> COMPLIANCE_REVIEW_TYPES { get; set; }
        public virtual ICollection<CONTRIBUTION_LIMIT_DISTRICT> CONTRIBUTION_LIMIT_DISTRICT { get; set; }
        public virtual ICollection<CONTRIBUTION_LIMIT_FORMULA> CONTRIBUTION_LIMIT_FORMULA { get; set; }
        public virtual ICollection<CONTRIBUTION_LIMIT_STATE> CONTRIBUTION_LIMIT_STATE { get; set; }
        public virtual ICollection<ENROLLMENT> ENROLLMENTs { get; set; }
        public virtual ICollection<ENROLLMENT_COUNTY> ENROLLMENT_COUNTY { get; set; }
        public virtual ICollection<ENROLLMENT_DISTRICT> ENROLLMENT_DISTRICT { get; set; }
        public virtual ICollection<ENROLLMENT_ED> ENROLLMENT_ED { get; set; }
        public virtual ICollection<FILING_EXEMPTION_DETAILS> FILING_EXEMPTION_DETAILS { get; set; }
        public virtual MASTER_LOOKUP MASTER_LOOKUP { get; set; }
        public virtual ICollection<REVIEW_TYPES> REVIEW_TYPES { get; set; }
        public virtual ICollection<TREASURER> TREASURERs { get; set; }
        public virtual ICollection<TREASURER_HISTORY> TREASURER_HISTORY { get; set; }
    }
}
