//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public MENU()
        {
            this.LOGIN_MENU_MAPPING = new HashSet<LOGIN_MENU_MAPPING>();
        }
    
        public int MENU_ID { get; set; }
        public string MENU_NAME { get; set; }
        public string SUBMENU_NAME { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<LOGIN_MENU_MAPPING> LOGIN_MENU_MAPPING { get; set; }
    }
}
