//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE_CENTER
    {
        public MESSAGE_CENTER()
        {
            this.CORRESPONDENCEs = new HashSet<CORRESPONDENCE>();
        }
    
        public int MESSAGE_CTR_ID { get; set; }
        public int LOGIN_ID { get; set; }
        public string MESSAGE_CTR_SUBJ { get; set; }
        public string MESSAGE_CTR_DESC { get; set; }
        public string MESSAGE_SENT_TO { get; set; }
        public string MESSAGE_CTR_TYPE { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<CORRESPONDENCE> CORRESPONDENCEs { get; set; }
    }
}
