//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUNICIPALITY_OFFICES
    {
        public MUNICIPALITY_OFFICES()
        {
            this.OFFICE_TERM_MAPPING = new HashSet<OFFICE_TERM_MAPPING>();
        }
    
        public int MUNICIPALITY_OFFICE_ID { get; set; }
        public int MUNICIPALITY_ID { get; set; }
        public int OFFICE_ID { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual MUNICIPALITY MUNICIPALITY { get; set; }
        public virtual ICollection<OFFICE_TERM_MAPPING> OFFICE_TERM_MAPPING { get; set; }
        public virtual OFFICE OFFICE { get; set; }
    }
}
