//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MUNICIPALITY
    {
        public MUNICIPALITY()
        {
            this.COMMITTEEs = new HashSet<COMMITTEE>();
            this.COMMITTEE_HISTORY = new HashSet<COMMITTEE_HISTORY>();
            this.ELECTIONs = new HashSet<ELECTION>();
            this.ELECTION_CANDIDATE = new HashSet<ELECTION_CANDIDATE>();
            this.ELECTION_CANDIDATE_HISTORY = new HashSet<ELECTION_CANDIDATE_HISTORY>();
            this.ELECTION_DATA_DEFAULT = new HashSet<ELECTION_DATA_DEFAULT>();
            this.ELECTION_OFFICE = new HashSet<ELECTION_OFFICE>();
            this.PETITIONs = new HashSet<PETITION>();
            this.POLITICAL_CALENDAR_DATES = new HashSet<POLITICAL_CALENDAR_DATES>();
            this.MUNICIPALITY_OFFICES = new HashSet<MUNICIPALITY_OFFICES>();
        }
    
        public int MUNICIPALITY_ID { get; set; }
        public int COUNTY_ID { get; set; }
        public int SUBD_TYPE_ID { get; set; }
        public string MUNICIPALITY_DESC { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<COMMITTEE> COMMITTEEs { get; set; }
        public virtual ICollection<COMMITTEE_HISTORY> COMMITTEE_HISTORY { get; set; }
        public virtual COUNTY COUNTY { get; set; }
        public virtual ICollection<ELECTION> ELECTIONs { get; set; }
        public virtual ICollection<ELECTION_CANDIDATE> ELECTION_CANDIDATE { get; set; }
        public virtual ICollection<ELECTION_CANDIDATE_HISTORY> ELECTION_CANDIDATE_HISTORY { get; set; }
        public virtual ICollection<ELECTION_DATA_DEFAULT> ELECTION_DATA_DEFAULT { get; set; }
        public virtual ICollection<ELECTION_OFFICE> ELECTION_OFFICE { get; set; }
        public virtual ICollection<PETITION> PETITIONs { get; set; }
        public virtual ICollection<POLITICAL_CALENDAR_DATES> POLITICAL_CALENDAR_DATES { get; set; }
        public virtual ICollection<MUNICIPALITY_OFFICES> MUNICIPALITY_OFFICES { get; set; }
        public virtual SUBDIVISION_TYPE SUBDIVISION_TYPE { get; set; }
    }
}
