//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NON_PARTICIPATION
    {
        public int NON_PART_ID { get; set; }
        public int ELECT_ID { get; set; }
        public long FILER_ID { get; set; }
        public System.DateTime SIGNED_DATE { get; set; }
        public System.DateTime RECEIVED_DATE { get; set; }
        public System.DateTime NON_PART_FROM { get; set; }
        public System.DateTime NON_PART_TO { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ELECTION ELECTION { get; set; }
    }
}
