//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJECTION
    {
        public OBJECTION()
        {
            this.CANDIDATE_OBJECTOR = new HashSet<CANDIDATE_OBJECTOR>();
            this.HEARINGs = new HashSet<HEARING>();
            this.SPECIFICATIONS = new HashSet<SPECIFICATION>();
        }
    
        public int OBJ_ID { get; set; }
        public int PET_FRM_MAP_ID { get; set; }
        public Nullable<long> COMMENT_ID { get; set; }
        public string OBJ_STATUS { get; set; }
        public Nullable<System.DateTime> OBJ_FILING_DATE { get; set; }
        public Nullable<System.DateTime> OBJ_SPEC_DUE_DATE { get; set; }
        public Nullable<int> OBJ_VOL_NUM { get; set; }
        public Nullable<int> OBJ_PAGE_NUM { get; set; }
        public Nullable<int> OBJ_SIGNATURE_NUM { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<CANDIDATE_OBJECTOR> CANDIDATE_OBJECTOR { get; set; }
        public virtual COMMENT COMMENT { get; set; }
        public virtual ICollection<HEARING> HEARINGs { get; set; }
        public virtual PETITION_FORM_MAPPING PETITION_FORM_MAPPING { get; set; }
        public virtual ICollection<SPECIFICATION> SPECIFICATIONS { get; set; }
    }
}
