//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFICE
    {
        public OFFICE()
        {
            this.COMMITTEEs = new HashSet<COMMITTEE>();
            this.COMMITTEE_HISTORY = new HashSet<COMMITTEE_HISTORY>();
            this.CONTRIBUTION_LIMIT = new HashSet<CONTRIBUTION_LIMIT>();
            this.ELECTION_CANDIDATE_HISTORY = new HashSet<ELECTION_CANDIDATE_HISTORY>();
            this.IE_COMM_SUPPORT_OPPOSE = new HashSet<IE_COMM_SUPPORT_OPPOSE>();
            this.MUNICIPALITY_OFFICES = new HashSet<MUNICIPALITY_OFFICES>();
            this.OFFICE_DISTRICT_MAPPING = new HashSet<OFFICE_DISTRICT_MAPPING>();
        }
    
        public int OFFICE_ID { get; set; }
        public int OFFICE_TYPE_ID { get; set; }
        public string OFFICE_DESC { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MASTER_OFFICE_STATUS { get; set; }
        public Nullable<int> MASTER_OFFICE_ID { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_DATE { get; set; }
        public Nullable<System.DateTime> INEFFECTIVE_DATE { get; set; }
    
        public virtual ICollection<COMMITTEE> COMMITTEEs { get; set; }
        public virtual ICollection<COMMITTEE_HISTORY> COMMITTEE_HISTORY { get; set; }
        public virtual ICollection<CONTRIBUTION_LIMIT> CONTRIBUTION_LIMIT { get; set; }
        public virtual ICollection<ELECTION_CANDIDATE_HISTORY> ELECTION_CANDIDATE_HISTORY { get; set; }
        public virtual ICollection<IE_COMM_SUPPORT_OPPOSE> IE_COMM_SUPPORT_OPPOSE { get; set; }
        public virtual ICollection<MUNICIPALITY_OFFICES> MUNICIPALITY_OFFICES { get; set; }
        public virtual ICollection<OFFICE_DISTRICT_MAPPING> OFFICE_DISTRICT_MAPPING { get; set; }
        public virtual OFFICE_TYPE OFFICE_TYPE { get; set; }
    }
}
