//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFICE_DISTRICT_MAPPING
    {
        public OFFICE_DISTRICT_MAPPING()
        {
            this.COMMITTEE_HISTORY = new HashSet<COMMITTEE_HISTORY>();
            this.ELECTED_OFFICIALS_ADDRS = new HashSet<ELECTED_OFFICIALS_ADDRS>();
            this.ELECTION_OFFICE = new HashSet<ELECTION_OFFICE>();
            this.IE_COMM_SUPPORT_OPPOSE = new HashSet<IE_COMM_SUPPORT_OPPOSE>();
            this.PARTY_CALL = new HashSet<PARTY_CALL>();
        }
    
        public int OFF_DIST_MAP_ID { get; set; }
        public int OFFICE_ID { get; set; }
        public string DISTRICT { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string LEG_DISTRICT { get; set; }
        public string WARD { get; set; }
        public string ELECT_DISTRICT { get; set; }
    
        public virtual ICollection<COMMITTEE_HISTORY> COMMITTEE_HISTORY { get; set; }
        public virtual ICollection<ELECTED_OFFICIALS_ADDRS> ELECTED_OFFICIALS_ADDRS { get; set; }
        public virtual ICollection<ELECTION_OFFICE> ELECTION_OFFICE { get; set; }
        public virtual ICollection<IE_COMM_SUPPORT_OPPOSE> IE_COMM_SUPPORT_OPPOSE { get; set; }
        public virtual OFFICE OFFICE { get; set; }
        public virtual ICollection<PARTY_CALL> PARTY_CALL { get; set; }
    }
}
