//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFICE_TYPE
    {
        public OFFICE_TYPE()
        {
            this.COMMITTEEs = new HashSet<COMMITTEE>();
            this.COMMITTEE_HISTORY = new HashSet<COMMITTEE_HISTORY>();
            this.ELECTIONs = new HashSet<ELECTION>();
            this.ELECTION_DATA_DEFAULT = new HashSet<ELECTION_DATA_DEFAULT>();
            this.FILING_PERIOD = new HashSet<FILING_PERIOD>();
            this.IE_COMM_SUPPORT_OPPOSE = new HashSet<IE_COMM_SUPPORT_OPPOSE>();
            this.IE_POLITICAL_COMMUNICATION = new HashSet<IE_POLITICAL_COMMUNICATION>();
            this.OFFICEs = new HashSet<OFFICE>();
            this.POLITICAL_CALENDAR_LABEL_MAP = new HashSet<POLITICAL_CALENDAR_LABEL_MAP>();
            this.REQUIRED_FILER = new HashSet<REQUIRED_FILER>();
        }
    
        public int OFFICE_TYPE_ID { get; set; }
        public string OFFICE_TYPE_DESC { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<COMMITTEE> COMMITTEEs { get; set; }
        public virtual ICollection<COMMITTEE_HISTORY> COMMITTEE_HISTORY { get; set; }
        public virtual ICollection<ELECTION> ELECTIONs { get; set; }
        public virtual ICollection<ELECTION_DATA_DEFAULT> ELECTION_DATA_DEFAULT { get; set; }
        public virtual ICollection<FILING_PERIOD> FILING_PERIOD { get; set; }
        public virtual ICollection<IE_COMM_SUPPORT_OPPOSE> IE_COMM_SUPPORT_OPPOSE { get; set; }
        public virtual ICollection<IE_POLITICAL_COMMUNICATION> IE_POLITICAL_COMMUNICATION { get; set; }
        public virtual ICollection<OFFICE> OFFICEs { get; set; }
        public virtual ICollection<POLITICAL_CALENDAR_LABEL_MAP> POLITICAL_CALENDAR_LABEL_MAP { get; set; }
        public virtual ICollection<REQUIRED_FILER> REQUIRED_FILER { get; set; }
    }
}
