//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTY_ELECTION_HISTORY
    {
        public int PARTY_ELECT_HIST_ID { get; set; }
        public int PARTY_ELECT_ID { get; set; }
        public int ELECTION_YEAR_ID { get; set; }
        public string PARTY_EMBLEM_IMG { get; set; }
        public int PARENT_PARTY_ID { get; set; }
        public string PARTY_COLOR { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ELECTION_YEAR ELECTION_YEAR { get; set; }
        public virtual ELECTION_YEAR ELECTION_YEAR1 { get; set; }
        public virtual PARTY_ELECTION PARTY_ELECTION { get; set; }
    }
}
