//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTY_CALL
    {
        public int PARTY_CALL_ID { get; set; }
        public Nullable<int> PARTY_ID { get; set; }
        public Nullable<int> ELECTION_YEAR_ID { get; set; }
        public int DELEGATE_NUM { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<int> COUNTY_ID { get; set; }
        public int OFF_DIST_MAP_ID { get; set; }
        public Nullable<int> OFF_DIST_MAP_ID2 { get; set; }
    
        public virtual COUNTY COUNTY { get; set; }
        public virtual ELECTION_YEAR ELECTION_YEAR { get; set; }
        public virtual OFFICE_DISTRICT_MAPPING OFFICE_DISTRICT_MAPPING { get; set; }
        public virtual PARTY PARTY { get; set; }
    }
}
