//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTY
    {
        public PARTY()
        {
            this.COUNTY_OFFICIALS = new HashSet<COUNTY_OFFICIALS>();
            this.PARTY_CALL = new HashSet<PARTY_CALL>();
            this.PETITION_HISTORY = new HashSet<PETITION_HISTORY>();
        }
    
        public int PARTY_ID { get; set; }
        public string PARTY_DESC { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<COUNTY_OFFICIALS> COUNTY_OFFICIALS { get; set; }
        public virtual ICollection<PARTY_CALL> PARTY_CALL { get; set; }
        public virtual ICollection<PETITION_HISTORY> PETITION_HISTORY { get; set; }
    }
}
