//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_NAME_MAPPING
    {
        public long PERSON_NAME_MAPPING_ID { get; set; }
        public long PERSON_ID { get; set; }
        public Nullable<int> TITLE_ID { get; set; }
        public string PERSON_FIRST_NAME { get; set; }
        public string PERSON_LAST_NAME { get; set; }
        public string PERSON_MIDDLE_NAME { get; set; }
        public string PERSON_SUFFIX { get; set; }
        public string PERSON_PREFIX { get; set; }
        public string R_RECORD_CREATED { get; set; }
        public string R_ACTIVE { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual PERSON PERSON { get; set; }
        public virtual TITLE TITLE { get; set; }
    }
}
