//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PET_FORM_COMMENTS_MAPPING
    {
        public long PET_FORM_COMMENTS_MAP_ID { get; set; }
        public int PET_FRM_MAP_ID { get; set; }
        public long COMMENT_ID { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual COMMENT COMMENT { get; set; }
        public virtual PETITION_FORM_MAPPING PETITION_FORM_MAPPING { get; set; }
    }
}
