//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PETITION
    {
        public PETITION()
        {
            this.BALLOT_CORRESPONDENCE = new HashSet<BALLOT_CORRESPONDENCE>();
            this.BALLOT_PROPOSALS = new HashSet<BALLOT_PROPOSALS>();
            this.CAPAS_PET_DEF_REG = new HashSet<CAPAS_PET_DEF_REG>();
            this.ELECTION_CAND_ADDR_MAPPING = new HashSet<ELECTION_CAND_ADDR_MAPPING>();
            this.ELECTION_CAND_CONTACT_MAPPING = new HashSet<ELECTION_CAND_CONTACT_MAPPING>();
            this.ELECTION_CAND_DOCUMENTATION = new HashSet<ELECTION_CAND_DOCUMENTATION>();
            this.ELECTION_CAND_MAPPING = new HashSet<ELECTION_CAND_MAPPING>();
            this.ELECTION_CAND_NAME_MAPPING = new HashSet<ELECTION_CAND_NAME_MAPPING>();
            this.ELECTION_CAND_SIGNATURE = new HashSet<ELECTION_CAND_SIGNATURE>();
            this.PET_COMMENTS_MAPPING = new HashSet<PET_COMMENTS_MAPPING>();
            this.PET_ELECTION_MAPPING = new HashSet<PET_ELECTION_MAPPING>();
            this.SBOE_RECOMMENDATIONS_DECISION = new HashSet<SBOE_RECOMMENDATIONS_DECISION>();
            this.PETITION_HISTORY = new HashSet<PETITION_HISTORY>();
            this.PETITION_VOLUME = new HashSet<PETITION_VOLUME>();
            this.PETITION_REVIEW = new HashSet<PETITION_REVIEW>();
        }
    
        public long PET_ID { get; set; }
        public int PET_TYPE_ID { get; set; }
        public Nullable<int> PARTY_ELECT_ID { get; set; }
        public Nullable<long> SCAN_DOC_ID { get; set; }
        public Nullable<long> PET_CORRECT_DEF { get; set; }
        public string LEGACY_BALLOT_TYPE { get; set; }
        public Nullable<int> LEGACY_PET_ID { get; set; }
        public Nullable<int> PET_TOT_NUM_VOL { get; set; }
        public Nullable<int> PET_TOT_NUM_PGS { get; set; }
        public Nullable<System.DateTime> PET_DATE_RECEIVED { get; set; }
        public string PET_RECEIVED_BY_USERID { get; set; }
        public Nullable<System.DateTime> PET_POST_MARK_DATE { get; set; }
        public string FILING_METHOD { get; set; }
        public string PET_DIST_TABLE_RCVD { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<int> MUNICIPALITY_ID { get; set; }
        public Nullable<System.DateTime> OBJECTION_DUE_DATE { get; set; }
    
        public virtual ICollection<BALLOT_CORRESPONDENCE> BALLOT_CORRESPONDENCE { get; set; }
        public virtual ICollection<BALLOT_PROPOSALS> BALLOT_PROPOSALS { get; set; }
        public virtual ICollection<CAPAS_PET_DEF_REG> CAPAS_PET_DEF_REG { get; set; }
        public virtual ICollection<ELECTION_CAND_ADDR_MAPPING> ELECTION_CAND_ADDR_MAPPING { get; set; }
        public virtual ICollection<ELECTION_CAND_CONTACT_MAPPING> ELECTION_CAND_CONTACT_MAPPING { get; set; }
        public virtual ICollection<ELECTION_CAND_DOCUMENTATION> ELECTION_CAND_DOCUMENTATION { get; set; }
        public virtual ICollection<ELECTION_CAND_MAPPING> ELECTION_CAND_MAPPING { get; set; }
        public virtual ICollection<ELECTION_CAND_NAME_MAPPING> ELECTION_CAND_NAME_MAPPING { get; set; }
        public virtual ICollection<ELECTION_CAND_SIGNATURE> ELECTION_CAND_SIGNATURE { get; set; }
        public virtual MUNICIPALITY MUNICIPALITY { get; set; }
        public virtual PARTY_ELECTION PARTY_ELECTION { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual ICollection<PET_COMMENTS_MAPPING> PET_COMMENTS_MAPPING { get; set; }
        public virtual ICollection<PET_ELECTION_MAPPING> PET_ELECTION_MAPPING { get; set; }
        public virtual PETITION_TYPE PETITION_TYPE { get; set; }
        public virtual SCAN_DOCUMENT SCAN_DOCUMENT { get; set; }
        public virtual ICollection<SBOE_RECOMMENDATIONS_DECISION> SBOE_RECOMMENDATIONS_DECISION { get; set; }
        public virtual ICollection<PETITION_HISTORY> PETITION_HISTORY { get; set; }
        public virtual ICollection<PETITION_VOLUME> PETITION_VOLUME { get; set; }
        public virtual ICollection<PETITION_REVIEW> PETITION_REVIEW { get; set; }
    }
}
