//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PETITION_HISTORY
    {
        public long PET_HIST_ID { get; set; }
        public long PET_ID { get; set; }
        public int ELECT_ID { get; set; }
        public int PET_TYPE_ID { get; set; }
        public int PARTY_ELECT_ID { get; set; }
        public int PARTY_ID { get; set; }
        public long SCAN_DOC_ID { get; set; }
        public Nullable<int> PET_TOT_NUM_VOL { get; set; }
        public Nullable<int> PET_TOT_NUM_PGS { get; set; }
        public Nullable<System.DateTime> PET_DATE_RECEIVED { get; set; }
        public string PET_RECEIVED_BY_USERID { get; set; }
        public Nullable<System.DateTime> PET_POST_MARK_DATE { get; set; }
        public Nullable<int> LEGACY_PET_ID { get; set; }
        public string LEGACY_BALLOT_TYPE { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ELECTION ELECTION { get; set; }
        public virtual PARTY PARTY { get; set; }
        public virtual PARTY_ELECTION PARTY_ELECTION { get; set; }
        public virtual PETITION PETITION { get; set; }
        public virtual PETITION_TYPE PETITION_TYPE { get; set; }
        public virtual SCAN_DOCUMENT SCAN_DOCUMENT { get; set; }
    }
}
