//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PETITION_FORM_MAPPING
    {
        public PETITION_FORM_MAPPING()
        {
            this.BALLOT_CORRESPONDENCE = new HashSet<BALLOT_CORRESPONDENCE>();
            this.ELECTION_CAND_ADDR_MAPPING = new HashSet<ELECTION_CAND_ADDR_MAPPING>();
            this.ELECTION_CAND_CONTACT_MAPPING = new HashSet<ELECTION_CAND_CONTACT_MAPPING>();
            this.ELECTION_CAND_MAPPING = new HashSet<ELECTION_CAND_MAPPING>();
            this.ELECTION_CAND_NAME_MAPPING = new HashSet<ELECTION_CAND_NAME_MAPPING>();
            this.ELECTION_CAND_SIGNATURE = new HashSet<ELECTION_CAND_SIGNATURE>();
            this.OBJECTIONS = new HashSet<OBJECTION>();
            this.PET_FORM_COMMENTS_MAPPING = new HashSet<PET_FORM_COMMENTS_MAPPING>();
            this.PETITION_REVIEW = new HashSet<PETITION_REVIEW>();
            this.SPECIFICATIONS = new HashSet<SPECIFICATION>();
        }
    
        public int PET_FRM_MAP_ID { get; set; }
        public Nullable<int> PET_FRM_TYPE_ID { get; set; }
        public long ELECT_CAND_ID { get; set; }
        public Nullable<long> SUB_ELECT_CAND_ID { get; set; }
        public Nullable<long> SCAN_DOC_ID { get; set; }
        public string PET_FRM_FILING_METHOD { get; set; }
        public Nullable<System.DateTime> PET_FRM_DATE_RECEIVED { get; set; }
        public Nullable<System.DateTime> PET_FRM_POSTMARK_DATE { get; set; }
        public string R_PET_FRM_STATUS { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<BALLOT_CORRESPONDENCE> BALLOT_CORRESPONDENCE { get; set; }
        public virtual ICollection<ELECTION_CAND_ADDR_MAPPING> ELECTION_CAND_ADDR_MAPPING { get; set; }
        public virtual ICollection<ELECTION_CAND_CONTACT_MAPPING> ELECTION_CAND_CONTACT_MAPPING { get; set; }
        public virtual ICollection<ELECTION_CAND_MAPPING> ELECTION_CAND_MAPPING { get; set; }
        public virtual ICollection<ELECTION_CAND_NAME_MAPPING> ELECTION_CAND_NAME_MAPPING { get; set; }
        public virtual ICollection<ELECTION_CAND_SIGNATURE> ELECTION_CAND_SIGNATURE { get; set; }
        public virtual ELECTION_CANDIDATE ELECTION_CANDIDATE { get; set; }
        public virtual ELECTION_CANDIDATE ELECTION_CANDIDATE1 { get; set; }
        public virtual ICollection<OBJECTION> OBJECTIONS { get; set; }
        public virtual ICollection<PET_FORM_COMMENTS_MAPPING> PET_FORM_COMMENTS_MAPPING { get; set; }
        public virtual PETITION_FORM_TYPE PETITION_FORM_TYPE { get; set; }
        public virtual ICollection<PETITION_REVIEW> PETITION_REVIEW { get; set; }
        public virtual ICollection<SPECIFICATION> SPECIFICATIONS { get; set; }
        public virtual SCAN_DOCUMENT SCAN_DOCUMENT { get; set; }
    }
}
