//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PETITION_VOLUME
    {
        public int PET_VOL_ID { get; set; }
        public long ELECT_CAND_ID { get; set; }
        public long PET_ID { get; set; }
        public int PET_VOL_NUM { get; set; }
        public int PET_NUM_SIGN { get; set; }
        public int PET_NUM_PAGES { get; set; }
        public Nullable<int> PET_SIGN_REJECTED { get; set; }
        public Nullable<int> PET_SIGN_ACCEPTED { get; set; }
        public int PAGE_FROM { get; set; }
        public int PAGE_TO { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual PETITION PETITION { get; set; }
    }
}
