//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PETITION_REVIEW
    {
        public PETITION_REVIEW()
        {
            this.CAPAS_PET_DEF_REG = new HashSet<CAPAS_PET_DEF_REG>();
        }
    
        public int PET_REVIEW_ID { get; set; }
        public int REVIEW_DETAILS_ID { get; set; }
        public long PET_ID { get; set; }
        public Nullable<int> PET_FRM_MAP_ID { get; set; }
        public int EXE_REV_ID { get; set; }
        public Nullable<int> PET_REVIEWER1_EMP_ID { get; set; }
        public string PET_REVIEWER2_EMP_ID { get; set; }
        public Nullable<int> HEARING_ID { get; set; }
        public Nullable<System.DateTime> PET_NOTICE_SENT { get; set; }
        public Nullable<System.DateTime> PET_CORR_DUE { get; set; }
        public Nullable<System.DateTime> PET_CORR_RECD { get; set; }
        public string PET_CORR_COVER_SHEET { get; set; }
        public Nullable<System.DateTime> PET_CORR_REVIEW_DATE { get; set; }
        public string PET_PROOF_BY { get; set; }
        public string PET_SCAN_BY { get; set; }
        public string R_HEARING { get; set; }
        public string R_COMM_REVIEW_STATUS { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<CAPAS_PET_DEF_REG> CAPAS_PET_DEF_REG { get; set; }
        public virtual EXECUTIVE_REVIEWER EXECUTIVE_REVIEWER { get; set; }
        public virtual HEARING HEARING { get; set; }
        public virtual PETITION PETITION { get; set; }
        public virtual PETITION_FORM_MAPPING PETITION_FORM_MAPPING { get; set; }
        public virtual REVIEW_DETAILS REVIEW_DETAILS { get; set; }
    }
}
