//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PETITION_FORM_TYPE
    {
        public PETITION_FORM_TYPE()
        {
            this.PETITION_FORM_MAPPING = new HashSet<PETITION_FORM_MAPPING>();
            this.REVIEW_TYPES = new HashSet<REVIEW_TYPES>();
        }
    
        public int PET_FRM_TYPE_ID { get; set; }
        public string PET_FRM_TYPE_DESC { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<PETITION_FORM_MAPPING> PETITION_FORM_MAPPING { get; set; }
        public virtual ICollection<REVIEW_TYPES> REVIEW_TYPES { get; set; }
    }
}
