//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PETITION_RELATED_FORMS
    {
        public int PET_REL_FRM_ID { get; set; }
        public int PET_FRM_MAP_ID { get; set; }
        public string R_PARTY_NAME { get; set; }
        public string R_TIMELY { get; set; }
        public string R_OFFICE_DISTRICT { get; set; }
        public string R_NUM_DESIGNATED { get; set; }
        public string R_CAND_NAME { get; set; }
        public string R_CAND_ADDR { get; set; }
        public string R_OLD_CAND_NAME { get; set; }
        public string R_ACKNOWLEDGED { get; set; }
        public string R_SIGNED { get; set; }
        public string R_MINUTES_FILED { get; set; }
        public string R_MINUTES_CERT { get; set; }
        public string R_CONSENT_APPEND { get; set; }
        public string R_CONSENT_SIGN { get; set; }
        public string R_AFFIDAVIT_SIGN { get; set; }
        public string R_VACANCY_CAUSE { get; set; }
        public string R_COMPLIANCE { get; set; }
        public string COMMENT { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
