//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLITICAL_CALENDAR_DATES
    {
        public int POL_CAL_DATE_ID { get; set; }
        public int POL_CAL_LBL_MAPPING_ID { get; set; }
        public int ELECTION_YEAR_ID { get; set; }
        public Nullable<int> COUNTY_ID { get; set; }
        public Nullable<int> MUNICIPALITY_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string POL_CAL_PARENT_MAPPING { get; set; }
        public Nullable<int> SIG_REQS { get; set; }
        public Nullable<System.TimeSpan> ELEC_HRS { get; set; }
        public string POL_CAL_LBL_LAW_NUMBER { get; set; }
        public string POL_CAL_INCLUDE { get; set; }
        public string POL_CAL_STATUS { get; set; }
        public string POL_CAL_WEB_STATUS { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual COUNTY COUNTY { get; set; }
        public virtual ELECTION_YEAR ELECTION_YEAR { get; set; }
        public virtual MUNICIPALITY MUNICIPALITY { get; set; }
    }
}
