//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLITICAL_CALENDAR_FORM_MAP
    {
        public POLITICAL_CALENDAR_FORM_MAP()
        {
            this.POLITICAL_CALENDAR_LABEL_MAP = new HashSet<POLITICAL_CALENDAR_LABEL_MAP>();
        }
    
        public int POL_CAL_FORM_MAP_ID { get; set; }
        public int POL_CAL_LBL_ID { get; set; }
        public int POL_CAL_HEADING_ID { get; set; }
        public int POL_CAL_SUB_HEADING_ID { get; set; }
        public int POL_CAL_FORMULA_ID { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual POLITICAL_CALENDAR_LABEL POLITICAL_CALENDAR_LABEL { get; set; }
        public virtual POLITICAL_CALENDAR_FORMULA POLITICAL_CALENDAR_FORMULA { get; set; }
        public virtual POLITICAL_CALENDAR_HEADING POLITICAL_CALENDAR_HEADING { get; set; }
        public virtual POLITICAL_CALENDAR_SUBHEADING POLITICAL_CALENDAR_SUBHEADING { get; set; }
        public virtual ICollection<POLITICAL_CALENDAR_LABEL_MAP> POLITICAL_CALENDAR_LABEL_MAP { get; set; }
    }
}
