//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PR_CONTRIBUTION
    {
        public long PR_CONTRIBUTION_ID { get; set; }
        public Nullable<long> FILING_TRANS_ID { get; set; }
        public string CONTRIBUTOR { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public Nullable<System.DateTime> DATEOFCONTRIBUTION { get; set; }
        public string RECIPIENTNAME { get; set; }
        public string FILING { get; set; }
        public string SCHEDULE { get; set; }
        public string OFFICEDESC { get; set; }
        public string DISTRICTID { get; set; }
        public string COUNTY { get; set; }
        public string MUNICIPALITYDESC { get; set; }
        public string COMMTYPEDESC { get; set; }
        public string CONTRIBUTORTYPE { get; set; }
        public string ELECTION_TYPE { get; set; }
        public string ELECTION_COUNTY { get; set; }
        public string ELECTION_MUNICIPALITY { get; set; }
        public string TRANSFER_TYPE_DESC { get; set; }
        public string FILTER_CAND_NAME { get; set; }
        public string FILTER_COMM_NAME { get; set; }
        public Nullable<double> FILTER_AMT_MIN { get; set; }
        public Nullable<double> FILTER_AMT_MAX { get; set; }
        public string FILTER_RPT_YEAR { get; set; }
        public string FILTER_ZIP_FROM { get; set; }
        public string FILTER_ZIP_TO { get; set; }
        public Nullable<System.DateTime> DATE_FROM { get; set; }
        public System.DateTime DATE_TO { get; set; }
        public string FLNG_ENT_ADDR1 { get; set; }
        public string FLNG_ENT_CITY { get; set; }
        public string FLNG_ENT_STATE { get; set; }
        public string FLNG_ENT_ZIP { get; set; }
        public string FLNG_ENT_COUNTRY { get; set; }
        public string CSV_Name_CONTRIBUTOR { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
