//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVIEW_TYPES
    {
        public REVIEW_TYPES()
        {
            this.REVIEW_DETAILS = new HashSet<REVIEW_DETAILS>();
        }
    
        public int REVIEW_TYPE_ID { get; set; }
        public int PET_FRM_TYPE_ID { get; set; }
        public int MASTER_TYPE_ID { get; set; }
        public string REVIEW_TYPE_DESC { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual MASTER_TYPE MASTER_TYPE { get; set; }
        public virtual PETITION_FORM_TYPE PETITION_FORM_TYPE { get; set; }
        public virtual ICollection<REVIEW_DETAILS> REVIEW_DETAILS { get; set; }
    }
}
