//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVIEW_DETAILS
    {
        public REVIEW_DETAILS()
        {
            this.PETITION_REVIEW = new HashSet<PETITION_REVIEW>();
        }
    
        public int REVIEW_DETAILS_ID { get; set; }
        public int REVIEW_TYPE_ID { get; set; }
        public Nullable<long> COMMENT_ID { get; set; }
        public string R_REVIEW_STATUS { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual COMMENT COMMENT { get; set; }
        public virtual ICollection<PETITION_REVIEW> PETITION_REVIEW { get; set; }
        public virtual REVIEW_TYPES REVIEW_TYPES { get; set; }
    }
}
