//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVIEW_DATE_TYPE_MAPPING
    {
        public int REVIEW_DATE_TYPE_MAP_ID { get; set; }
        public long REVIEW_COMP_ID { get; set; }
        public int REVIEW_DATE_TYPE_ID { get; set; }
        public System.DateTime REVIEW_TYPE_DATE { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual REVIEW_DATE_TYPE_MAPPING REVIEW_DATE_TYPE_MAPPING1 { get; set; }
        public virtual REVIEW_DATE_TYPE_MAPPING REVIEW_DATE_TYPE_MAPPING2 { get; set; }
    }
}
