//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVIEW_CORRESPONDENCE_REISSUE_HISTORY
    {
        public int REVIEW_CORR_REISSUE_HISTORY_ID { get; set; }
        public int REVIEW_CORR_REISSUE_ID { get; set; }
        public long REVIEW_CORES_ID { get; set; }
        public System.DateTime CORES_REISSUE_DATE { get; set; }
        public Nullable<int> REVIEW_COMP_ID { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
