//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVIEW_FILINGS
    {
        public long REVIEW_FILINGS_ID { get; set; }
        public int NUMBER_TRANS { get; set; }
        public Nullable<int> REVIEW_STATUS_ID { get; set; }
        public Nullable<System.DateTime> SUBMIT_DATE { get; set; }
        public string R_AMEND { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public long REVIEW_FILER_ID { get; set; }
        public Nullable<long> FILINGS_ID { get; set; }
    }
}
