//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCAN_DOCUMENT
    {
        public SCAN_DOCUMENT()
        {
            this.CORRESPONDENCEs = new HashSet<CORRESPONDENCE>();
            this.FILER_SCAN_MAPPING = new HashSet<FILER_SCAN_MAPPING>();
            this.FILING_DOCUMENTS = new HashSet<FILING_DOCUMENTS>();
            this.PETITIONs = new HashSet<PETITION>();
            this.PETITION_FORM_MAPPING = new HashSet<PETITION_FORM_MAPPING>();
            this.PETITION_HISTORY = new HashSet<PETITION_HISTORY>();
        }
    
        public long SCAN_DOC_ID { get; set; }
        public Nullable<int> FORM_ID { get; set; }
        public string SCAN_DOC_DESC { get; set; }
        public string SCAN_DOC_FILE_NAME { get; set; }
        public byte[] SCAN_DOC_IMG { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<CORRESPONDENCE> CORRESPONDENCEs { get; set; }
        public virtual ICollection<FILER_SCAN_MAPPING> FILER_SCAN_MAPPING { get; set; }
        public virtual ICollection<FILING_DOCUMENTS> FILING_DOCUMENTS { get; set; }
        public virtual FORM FORM { get; set; }
        public virtual ICollection<PETITION> PETITIONs { get; set; }
        public virtual ICollection<PETITION_FORM_MAPPING> PETITION_FORM_MAPPING { get; set; }
        public virtual ICollection<PETITION_HISTORY> PETITION_HISTORY { get; set; }
    }
}
