//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    
    public partial class SP_I_FilingTrans_Public_Fund_Payment
    {
        public Nullable<long> AG_FILING_TRANS_ID { get; set; }
    }
}
