//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    
    public partial class SP_S_ItemizedWeeklyClaimSubTrans
    {
        public string ADDR_CITY { get; set; }
        public string ADDR_STATE { get; set; }
        public string CONTRIBUTOR_NAME { get; set; }
        public string CREATED_DATE { get; set; }
        public string DIST_OFF_CAND_BAL_PROP { get; set; }
        public string FILING_CAT_SUBTYPE { get; set; }
        public Nullable<long> FILING_TRANS_ID { get; set; }
        public string IE_DESC { get; set; }
        public string LOAN_LIB_NUMBER { get; set; }
        public double ORG_AMT { get; set; }
        public string SCHED_DATE { get; set; }
        public string TRANS_EXPLNTN { get; set; }
        public string TRANS_MAPPING { get; set; }
        public string TRANS_NUMBER { get; set; }
        public string TREASURER_NAME { get; set; }
    }
}
