//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    
    public partial class SP_S_Loan_Repayment_Amount_Validation
    {
        public string ORG_AMT { get; set; }
        public string ORIGINAL_AMOUNT { get; set; }
        public Nullable<System.DateTime> ORG_DATE { get; set; }
    }
}
