//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPECIFICATION
    {
        public int SPEC_ID { get; set; }
        public int OBJ_ID { get; set; }
        public int PET_FRM_MAP_ID { get; set; }
        public string SPEC_IN_TIME { get; set; }
        public string SPEC_PROOF_SERV { get; set; }
        public string SPEC_MATCH_OBJTR_FIRST_NAME { get; set; }
        public string SPEC_MATCH_OBJTR_LAST_NAME { get; set; }
        public string SPEC_MATCH_OBJTR_MIDDLE_NAME { get; set; }
        public string SPEC_MATCH_OBJTR_SUFFIX { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual OBJECTION OBJECTION { get; set; }
        public virtual PETITION_FORM_MAPPING PETITION_FORM_MAPPING { get; set; }
    }
}
