//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATE_COMMITTEE
    {
        public int STATE_COMM_ID { get; set; }
        public long PERSON_ID { get; set; }
        public long ADDR_ID { get; set; }
        public int PARTY_ELECT_ID { get; set; }
        public string STATE_COMM_NAME { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ADDRESS ADDRESS { get; set; }
        public virtual ADDRESS ADDRESS1 { get; set; }
        public virtual PARTY_ELECTION PARTY_ELECTION { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
