//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUB_TREASURER_HISTORY
    {
        public int SUB_TREAS_HIST_ID { get; set; }
        public Nullable<long> SUB_TREAS_ID { get; set; }
        public Nullable<System.DateTime> SUB_TREAS_REG_DATE { get; set; }
        public Nullable<System.DateTime> SUB_TREAS_HIST_TERM_DATE { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual SUB_TREASURER SUB_TREASURER { get; set; }
    }
}
