//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPORTING_DOCUMENTS
    {
        public SUPPORTING_DOCUMENTS()
        {
            this.CANDIDATE_COMMITTEE_AUTH = new HashSet<CANDIDATE_COMMITTEE_AUTH>();
        }
    
        public int SUPPORT_DOC_ID { get; set; }
        public Nullable<long> FILER_ID { get; set; }
        public Nullable<long> FILINGS_ID { get; set; }
        public Nullable<long> ELECT_CAND_ID { get; set; }
        public string TRANS_NUMBER { get; set; }
        public Nullable<int> FILING_METHOD_ID { get; set; }
        public Nullable<int> FORM_ID { get; set; }
        public Nullable<int> DOC_TYPE_ID { get; set; }
        public Nullable<long> SCAN_DOC_ID { get; set; }
        public string SUPPORT_DOC_CMTS { get; set; }
        public string FILE_TYPE { get; set; }
        public string FILE_SIZE { get; set; }
        public Nullable<System.DateTime> DATE_FILED { get; set; }
        public Nullable<System.DateTime> POST_MARK_DATE { get; set; }
        public string R_AMEND { get; set; }
        public string R_STATUS { get; set; }
        public string APPROVAL_STATUS { get; set; }
        public Nullable<int> FILER_PURPOSE_ID { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public Nullable<int> COMM_TYPE_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<long> SUB_TREAS_ID { get; set; }
        public Nullable<System.DateTime> DATE_CERTIFIED { get; set; }
        public Nullable<int> ELECTION_YEAR_ID { get; set; }
        public string CABINET_LOCATION { get; set; }
        public Nullable<long> S3_ID { get; set; }
    
        public virtual ICollection<CANDIDATE_COMMITTEE_AUTH> CANDIDATE_COMMITTEE_AUTH { get; set; }
        public virtual COMMUNICATION_TYPE COMMUNICATION_TYPE { get; set; }
        public virtual DOCUMENT_TYPE DOCUMENT_TYPE { get; set; }
        public virtual ELECTION_CANDIDATE ELECTION_CANDIDATE { get; set; }
        public virtual FILING_METHOD FILING_METHOD { get; set; }
        public virtual FORM FORM { get; set; }
    }
}
