//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPORTED_CANDIDATE_MAPPING
    {
        public int SUP_CAND_MAP_ID { get; set; }
        public long ELECT_CAND_ID { get; set; }
        public Nullable<long> SUPPORTED_CAND_ID { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ELECTION_CANDIDATE ELECTION_CANDIDATE { get; set; }
        public virtual ELECTION_CANDIDATE ELECTION_CANDIDATE1 { get; set; }
    }
}
