//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMPTABLE
    {
        public long FILINGS_ID { get; set; }
        public int POL_CAL_DATE_ID { get; set; }
        public int REPORT_YEAR_ID { get; set; }
        public int OFFICE_TYPE_ID { get; set; }
        public int ELECT_TYPE_ID { get; set; }
        public int DISCLOSURE_TYPE_ID { get; set; }
        public int DISCLOSURE_PERIOD_ID { get; set; }
        public int REPORT_YEAR { get; set; }
        public string OFFICE_TYPE_DESC { get; set; }
        public string ELECT_TYPE_DESC { get; set; }
        public Nullable<System.DateTime> ELECT_DATE { get; set; }
        public string DISCLOSURE_TYPE { get; set; }
        public string DISCLOSURE_PERIOD { get; set; }
        public string AMENDED { get; set; }
        public Nullable<System.DateTime> SUBMIT_DATE { get; set; }
        public string R_STATUS { get; set; }
    }
}
