//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TERMINATION_DETAILS
    {
        public TERMINATION_DETAILS()
        {
            this.TERMINATION_REVIEW = new HashSet<TERMINATION_REVIEW>();
        }
    
        public int TERM_DETAILS_ID { get; set; }
        public Nullable<long> CAND_ID { get; set; }
        public Nullable<long> COMM_ID { get; set; }
        public Nullable<long> FILINGS_ID { get; set; }
        public Nullable<long> COMMENT_ID { get; set; }
        public string R_REVIEW_COMPLETE { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual COMMENT COMMENT { get; set; }
        public virtual COMMITTEE COMMITTEE { get; set; }
        public virtual ICollection<TERMINATION_REVIEW> TERMINATION_REVIEW { get; set; }
    }
}
