//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TREASURER
    {
        public TREASURER()
        {
            this.COM_TREAS_SUBTREAS_MAPPING = new HashSet<COM_TREAS_SUBTREAS_MAPPING>();
            this.COMMITTEEs = new HashSet<COMMITTEE>();
            this.COMMITTEE_HISTORY = new HashSet<COMMITTEE_HISTORY>();
            this.COMMITTEE_TREASURER_MAPPING = new HashSet<COMMITTEE_TREASURER_MAPPING>();
            this.CORRESPONDENCEs = new HashSet<CORRESPONDENCE>();
            this.ELECTION_CANDIDATE = new HashSet<ELECTION_CANDIDATE>();
            this.FILER_CONVERSION_MAPPING = new HashSet<FILER_CONVERSION_MAPPING>();
            this.TREASURER_HISTORY = new HashSet<TREASURER_HISTORY>();
        }
    
        public long TREAS_ID { get; set; }
        public long PERSON_ID { get; set; }
        public Nullable<int> MASTER_TYPE_ID { get; set; }
        public Nullable<int> AUTH_KEY { get; set; }
        public Nullable<System.DateTime> TREAS_REG_DATE { get; set; }
        public string TREAS_OCCUPATION { get; set; }
        public string TREAS_EMPLOYER { get; set; }
        public string R_CREATE_USER_ID { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    
        public virtual ICollection<COM_TREAS_SUBTREAS_MAPPING> COM_TREAS_SUBTREAS_MAPPING { get; set; }
        public virtual ICollection<COMMITTEE> COMMITTEEs { get; set; }
        public virtual ICollection<COMMITTEE_HISTORY> COMMITTEE_HISTORY { get; set; }
        public virtual ICollection<COMMITTEE_TREASURER_MAPPING> COMMITTEE_TREASURER_MAPPING { get; set; }
        public virtual ICollection<CORRESPONDENCE> CORRESPONDENCEs { get; set; }
        public virtual ICollection<ELECTION_CANDIDATE> ELECTION_CANDIDATE { get; set; }
        public virtual ICollection<FILER_CONVERSION_MAPPING> FILER_CONVERSION_MAPPING { get; set; }
        public virtual MASTER_TYPE MASTER_TYPE { get; set; }
        public virtual PERSON PERSON { get; set; }
        public virtual ICollection<TREASURER_HISTORY> TREASURER_HISTORY { get; set; }
    }
}
