//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_BUP_FILER_DATA_HEADER
    {
        public string FILER_ID { get; set; }
        public string FILER_NAME { get; set; }
        public string COMPLIANCE_TYPE { get; set; }
        public string FILER_TYPE { get; set; }
        public string FILER_STATUS { get; set; }
        public string COMMITTEE_TYPE_DESC { get; set; }
        public string OFFICE_DESC { get; set; }
        public string DISTRICT { get; set; }
        public string COUNTY { get; set; }
        public string MUNICIPALITY { get; set; }
        public string TREASURER_FIRST_NAME { get; set; }
        public string TREASURER_MIDDLE_NAME { get; set; }
        public string TREASURER_LAST_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIPCODE { get; set; }
    }
}
