//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_BCP_PMF_WEEKLY_SUBMISIONS_JOB_HEADER
    {
        public string FILER_ID { get; set; }
        public string FILER_NAME { get; set; }
        public string COMMITTEE_TYPE_DESCRIPTION { get; set; }
        public string REPORT_YEAR { get; set; }
        public string ELECTION_TYPE { get; set; }
        public string REPORT_TYPE { get; set; }
        public string ELECTION_DATE { get; set; }
        public string OFFICE { get; set; }
        public string DISTRICT { get; set; }
        public string DISCLOSURE_TYPE { get; set; }
        public string DISCLOSURE_PERIOD { get; set; }
        public string SUBMITTED_DATE_AND_TIME { get; set; }
        public string AMENDED { get; set; }
        public string COUNTY { get; set; }
        public string MUNICIPALITY { get; set; }
        public string FILING_MEDIA { get; set; }
        public string NUMBER_OF_TRANSACTIONS { get; set; }
        public string AUDITOR { get; set; }
    }
}
