//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_BCP_PCFB_JOB
    {
        public string FILER_ID { get; set; }
        public string COMMITTEE_NAME { get; set; }
        public string REPORT_YEAR { get; set; }
        public string REPORT_TYPE { get; set; }
        public string DISCLOSURE_TYPE { get; set; }
        public string DISCLOSURE_PERIOD { get; set; }
        public string DOCUMENT_UPLOADED_DATE { get; set; }
    }
}
