//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_BANKINFORMATION
    {
        public int BANK_ID { get; set; }
        public Nullable<int> ACCOUNT_TYPE_ID { get; set; }
        public long ADDR_ID { get; set; }
        public Nullable<int> CONTACT_ID { get; set; }
        public string BANK_ROUTING_NUM { get; set; }
        public string BANK_ACCOUNT_NUM { get; set; }
        public string BANK_NAME { get; set; }
        public string R_STATUS { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime CREATED_DATE { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
    }
}
