//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_BCP_ENFORCEMENT_JOB
    {
        public string LEGACY_FILER_ID { get; set; }
        public long FILER_ID { get; set; }
        public Nullable<long> COMM_ID { get; set; }
        public string COMMITTEE_NAME { get; set; }
        public string TREASURER_TYPE { get; set; }
        public Nullable<long> TREAS_ID { get; set; }
        public string TF_NAME { get; set; }
        public string TM_NAME { get; set; }
        public string TL_NAME { get; set; }
        public Nullable<System.DateTime> DATE_FILING_DUE { get; set; }
        public Nullable<System.DateTime> ENFORCEMENT_DATE { get; set; }
        public Nullable<System.DateTime> SIGNED_DATE { get; set; }
        public string INDEX_NUMBER { get; set; }
        public Nullable<double> ENFORCEMENT_AMOUNT { get; set; }
        public Nullable<double> PROCESS_SERVER_COST { get; set; }
        public Nullable<double> PENALTY { get; set; }
        public Nullable<double> POSTAGE { get; set; }
        public Nullable<double> REDUCED_AMOUNT { get; set; }
        public Nullable<double> AMOUNT_PAID { get; set; }
        public Nullable<System.DateTime> PAID_DATE { get; set; }
        public Nullable<long> RECEIPT_NUMBER { get; set; }
        public Nullable<int> JUDGMENT_STATUS_ID { get; set; }
        public string EXPLANATION { get; set; }
        public string ADDRESS_1 { get; set; }
        public string ADDRESS_2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public Nullable<int> CORES_TYPE_ID { get; set; }
        public Nullable<int> FILING_PERIOD_ID { get; set; }
        public string COMMENTS_DESC { get; set; }
    }
}
