//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_BUP_ALL_HEADER_ENFORCEMENT_WITH_SUBMITDATE
    {
        public string FILER_ID { get; set; }
        public string FILER_PREVIOUS_ID { get; set; }
        public string CAND_COMM_NAME { get; set; }
        public string ELECTION_YEAR { get; set; }
        public string ELECTION_TYPE { get; set; }
        public string COUNTY_DESC { get; set; }
        public string FILING_ABBREV { get; set; }
        public string FILING_DESC { get; set; }
        public string R_AMEND { get; set; }
        public string FILING_CAT_DESC { get; set; }
        public string FILING_SCHED_ABBREV { get; set; }
        public string FILING_SCHED_DESC { get; set; }
        public string LOAN_LIB_NUMBER { get; set; }
        public string TRANS_NUMBER { get; set; }
        public string TRANS_MAPPING { get; set; }
        public string SCHED_DATE { get; set; }
        public string ORG_DATE { get; set; }
        public string CNTRBR_TYPE_DESC { get; set; }
        public string CNTRBN_TYPE_DESC { get; set; }
        public string TRANSFER_TYPE_DESC { get; set; }
        public string RECEIPT_TYPE_DESC { get; set; }
        public string RECEIPT_CODE_DESC { get; set; }
        public string PURPOSE_CODE_DESC { get; set; }
        public string R_SUBCONTRACTOR { get; set; }
        public string FLNG_ENT_NAME { get; set; }
        public string FLNG_ENT_FIRST_NAME { get; set; }
        public string FLNG_ENT_MIDDLE_NAME { get; set; }
        public string FLNG_ENT_LAST_NAME { get; set; }
        public string FLNG_ENT_ADDR1 { get; set; }
        public string FLNG_ENT_CITY { get; set; }
        public string FLNG_ENT_STATE { get; set; }
        public string FLNG_ENT_ZIP { get; set; }
        public string FLNG_ENT_COUNTRY { get; set; }
        public string PAYMENT_TYPE_DESC { get; set; }
        public string PAY_NUMBER { get; set; }
        public string OWED_AMT { get; set; }
        public string ORG_AMT { get; set; }
        public string LOAN_OTHER_DESC { get; set; }
        public string TRANS_EXPLNTN { get; set; }
        public string R_ITEMIZED { get; set; }
        public string R_LIABILITY { get; set; }
        public string ELECTION_YEAR_R { get; set; }
        public string OFFICE_DESC { get; set; }
        public string DISTRICT { get; set; }
        public string DIST_OFF_CAND_BAL_PROP { get; set; }
        public string SUBMIT_DATE { get; set; }
    }
}
