//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CountyBoards
    {
        public int COUNTY_ID { get; set; }
        public string CNTY_BOARD { get; set; }
        public string CNTY_DESC { get; set; }
        public string ADDR_ADDR1 { get; set; }
        public string ADDR_ADDR2 { get; set; }
        public string ADDR_CITY { get; set; }
        public string ADDR_STATE { get; set; }
        public string ADDR_ZIP { get; set; }
        public long PERSON_ID { get; set; }
        public string PERSON_PREFIX { get; set; }
        public string PERSON_FIRST_NAME { get; set; }
        public string PERSON_LAST_NAME { get; set; }
        public string PERSON_MIDDLE_NAME { get; set; }
        public string PERSON_SUFFIX { get; set; }
        public string TITLE_DESC { get; set; }
        public string BEST_CONTACT_DESC { get; set; }
    }
}
