//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CONTRIBUTIONS_FILING_TRANS
    {
        public long FILING_TRANS_ID { get; set; }
        public Nullable<double> org_amt { get; set; }
        public Nullable<System.DateTime> SCHED_DATE { get; set; }
        public Nullable<long> FLNG_ENT_ID { get; set; }
        public long FILINGS_ID { get; set; }
        public Nullable<int> FILING_SCHED_ID { get; set; }
        public Nullable<int> CNTRBR_TYPE_ID { get; set; }
        public string R_STATUS { get; set; }
        public Nullable<int> TRANSFER_TYPE_ID { get; set; }
        public Nullable<int> OFFICE_TYPE_ID { get; set; }
        public Nullable<long> COMM_ID { get; set; }
        public Nullable<long> CAND_ID { get; set; }
        public string FLNG_ENT_NAME { get; set; }
        public string FLNG_ENT_FIRST_NAME { get; set; }
        public string FLNG_ENT_MIDDLE_NAME { get; set; }
        public string FLNG_ENT_LAST_NAME { get; set; }
        public Nullable<int> OFFICE_ID { get; set; }
        public string DISTRICT { get; set; }
        public Nullable<int> COUNTY_ID { get; set; }
        public Nullable<int> MUNICIPALITY_ID { get; set; }
        public string FLNG_ENT_ZIP { get; set; }
    }
}
