//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CandidateList
    {
        public long ELECT_CAND_ID { get; set; }
        public int ELECTION_YEAR_ID { get; set; }
        public int elect_year { get; set; }
        public int ELECT_TYPE_ID { get; set; }
        public string elect_type_desc { get; set; }
        public int OFFICE_TYPE_ID { get; set; }
        public string office_type_desc { get; set; }
        public Nullable<int> OFFICE_ID { get; set; }
        public string office_desc { get; set; }
        public string DIST_ID { get; set; }
        public Nullable<int> COUNTY_ID { get; set; }
        public string cnty_desc { get; set; }
        public string subd_desc { get; set; }
        public Nullable<int> MUNICIPALITY_ID { get; set; }
        public string municipality_desc { get; set; }
        public int PARTY_ID { get; set; }
        public string party_desc { get; set; }
        public string party_symbol { get; set; }
        public string person_prefix { get; set; }
        public string PersonFirstName { get; set; }
        public string PersonMiddleName { get; set; }
        public string PersonLastName { get; set; }
        public string person_suffix { get; set; }
        public string addr_str_num { get; set; }
        public string addr_str_name { get; set; }
        public string addr_addr1 { get; set; }
        public string addr_addr2 { get; set; }
        public string addr_city { get; set; }
        public string addr_state { get; set; }
        public string addr_zip { get; set; }
        public string addr_zip4 { get; set; }
        public string BusinessStrNum { get; set; }
        public string BusinessStrName { get; set; }
        public string BusinessAddr1 { get; set; }
        public string BusinessAddr2 { get; set; }
        public string BusinessCity { get; set; }
        public string BusinessState { get; set; }
        public string BusinessZip { get; set; }
        public string BusinessZip4 { get; set; }
        public string CandidateFirstName { get; set; }
        public string CandidateMiddleName { get; set; }
        public string CandidateLastName { get; set; }
        public string pet_frm_type_desc { get; set; }
        public int pet_frm_type_id { get; set; }
        public string DueDate { get; set; }
        public string DateFiled { get; set; }
        public string DatePostMark { get; set; }
        public string ObjectionFirstName { get; set; }
        public string ObjectionMiddleName { get; set; }
        public string ObjectionLastName { get; set; }
        public string BALLOT_TYPE_DESC { get; set; }
        public string ballot_fname { get; set; }
        public string ballot_mname { get; set; }
        public string ballot_lname { get; set; }
        public string CAND_STATUS { get; set; }
    }
}
