//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CandidateCommittee
    {
        public long cand_comm_id { get; set; }
        public Nullable<long> comm_id { get; set; }
        public Nullable<long> CAND_ID { get; set; }
        public Nullable<int> office_id { get; set; }
        public string comm_name { get; set; }
        public string CandidatePrefix { get; set; }
        public string CandidateFirstName { get; set; }
        public string CandidateLastName { get; set; }
        public string CandidateMiddleName { get; set; }
        public string CandidateSuffix { get; set; }
        public Nullable<int> OFFICE_TYPE_ID { get; set; }
        public string OFFICE_TYPE_DESC { get; set; }
        public string office_desc { get; set; }
        public string DIST_ID { get; set; }
        public Nullable<int> county_id { get; set; }
        public string cnty_board { get; set; }
        public string CNTY_DESC { get; set; }
        public Nullable<int> municipality_id { get; set; }
        public string subd_desc { get; set; }
        public string municipality_desc { get; set; }
        public Nullable<long> FILER_ID { get; set; }
    }
}
