//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CONTRIBUTIONS
    {
        public long Filing_Trans_ID { get; set; }
        public string CONTRIBUTOR { get; set; }
        public string CONTRIBUTOR_NAME { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<System.DateTime> DATEOFCONTRIBUTION { get; set; }
        public string RECIPIENTNAME { get; set; }
        public string FILING { get; set; }
        public string SCHEDULE { get; set; }
        public string OFFICEDESC { get; set; }
        public string DISTRICTID { get; set; }
        public string COUNTY { get; set; }
        public string MUNICIPALITYDESC { get; set; }
        public string COMMTYPEDESC { get; set; }
        public string CONTRIBUTORTYPE { get; set; }
        public string ElectionType { get; set; }
        public string ELECTION_COUNTY { get; set; }
        public string ELECTION_MUNICIPALITY { get; set; }
        public string TRANSFER_TYPE_DESC { get; set; }
        public string FLNG_ENT_ADDR1 { get; set; }
        public string FLNG_ENT_CITY { get; set; }
        public string FLNG_ENT_STATE { get; set; }
        public string FLNG_ENT_ZIP { get; set; }
        public string FLNG_ENT_COUNTRY { get; set; }
        public string CSV_Name_CONTRIBUTOR { get; set; }
        public Nullable<int> OFFICE_TYPE_ID { get; set; }
        public Nullable<long> COMM_ID { get; set; }
        public Nullable<long> CAND_ID { get; set; }
        public Nullable<int> OFFICE_ID { get; set; }
        public string DISTRICT { get; set; }
        public Nullable<int> COUNTY_ID { get; set; }
        public Nullable<int> MUNICIPALITY_ID { get; set; }
        public Nullable<int> CNTRBR_TYPE_ID { get; set; }
    }
}
