//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Filings
    {
        public Nullable<long> FILING_TRANS_ID { get; set; }
        public long FILINGS_ID { get; set; }
        public Nullable<int> FILING_CAT_ID { get; set; }
        public Nullable<int> office_id { get; set; }
        public long filer_id { get; set; }
        public Nullable<long> CAND_ID { get; set; }
        public Nullable<long> COMM_ID { get; set; }
        public Nullable<int> COMM_TYPE_ID { get; set; }
        public string COMM_TYPE_DESC { get; set; }
        public string comm_name { get; set; }
        public string STATUS { get; set; }
        public string CandidatePrefix { get; set; }
        public string CandidateFirstName { get; set; }
        public string CandidateLastName { get; set; }
        public string CandidateMiddleName { get; set; }
        public string CandidateSuffix { get; set; }
        public Nullable<int> OFFICE_TYPE_ID { get; set; }
        public string OFFICE_TYPE_DESC { get; set; }
        public string office_desc { get; set; }
        public string DIST_ID { get; set; }
        public Nullable<int> county_id { get; set; }
        public string cnty_board { get; set; }
        public string CNTY_DESC { get; set; }
        public Nullable<int> municipality_id { get; set; }
        public string subd_desc { get; set; }
        public string municipality_desc { get; set; }
        public Nullable<int> ELECTION_YEAR_ID { get; set; }
        public Nullable<int> elect_year { get; set; }
        public string elect_type_desc { get; set; }
        public string filing_cat_desc { get; set; }
        public string FILING_CAT_SUBTYPE { get; set; }
        public Nullable<int> FILING_TYPE_ID { get; set; }
        public string filing_desc { get; set; }
        public string filing_abbrev { get; set; }
        public System.DateTime created_date { get; set; }
        public string filing_sched_abbrev { get; set; }
        public string FILING_SCHED_DESC { get; set; }
        public Nullable<int> CNTRBR_TYPE_ID { get; set; }
        public string CNTRBR_TYPE_DESC { get; set; }
        public string cntrbr_type_abbrev { get; set; }
        public string cntrbn_type_abbrev { get; set; }
        public string payment_type_abbrev { get; set; }
        public string RECEIPT_TYPE_ABBREV { get; set; }
        public string purpose_code_abbrev { get; set; }
        public string PURPOSE_CODE_DESC { get; set; }
        public string transfer_type_abbrev { get; set; }
        public Nullable<int> trans_code { get; set; }
        public Nullable<System.DateTime> sched_date { get; set; }
        public Nullable<System.DateTime> org_date { get; set; }
        public Nullable<System.DateTime> pay_date { get; set; }
        public string pay_number { get; set; }
        public Nullable<double> org_amt { get; set; }
        public Nullable<double> owed_amt { get; set; }
        public string trans_desc { get; set; }
        public string trans_explntn { get; set; }
        public Nullable<System.DateTime> election_date { get; set; }
        public string election_type { get; set; }
        public string election_year { get; set; }
        public string dist_off_cand_bal_prop { get; set; }
        public string r_bank_loan { get; set; }
        public string r_status { get; set; }
        public Nullable<int> LOAN_OTHER_ID { get; set; }
        public string LOAN_OTHER_ABBREV { get; set; }
        public string LOAN_OTHER_DESC { get; set; }
        public string flng_ent_name { get; set; }
        public string flng_ent_first_name { get; set; }
        public string flng_ent_middle_name { get; set; }
        public string flng_ent_last_name { get; set; }
        public string flng_ent_str_num { get; set; }
        public string flng_ent_str_name { get; set; }
        public string flng_ent_addr1 { get; set; }
        public string flng_ent_addr2 { get; set; }
        public string flng_ent_city { get; set; }
        public string flng_ent_state { get; set; }
        public string flng_ent_zip { get; set; }
        public string flng_ent_occupation { get; set; }
        public string flng_ent_employer { get; set; }
        public Nullable<int> FILING_SCHED_ID { get; set; }
        public Nullable<System.DateTime> SUBMIT_DATE { get; set; }
        public string R_AMEND { get; set; }
    }
}
