//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Filings_AutoComplete
    {
        public Nullable<long> FILING_TRANS_ID { get; set; }
        public Nullable<int> office_id { get; set; }
        public long filer_id { get; set; }
        public Nullable<long> CAND_ID { get; set; }
        public Nullable<long> COMM_ID { get; set; }
        public Nullable<int> COMM_TYPE_ID { get; set; }
        public string comm_name { get; set; }
        public string STATUS { get; set; }
        public string CandidateFirstName { get; set; }
        public string CandidateLastName { get; set; }
        public string CandidateMiddleName { get; set; }
        public Nullable<int> OFFICE_TYPE_ID { get; set; }
        public string office_desc { get; set; }
        public string dist_id { get; set; }
        public Nullable<int> county_id { get; set; }
        public Nullable<int> municipality_id { get; set; }
        public string flng_ent_name { get; set; }
        public string flng_ent_first_name { get; set; }
        public string flng_ent_middle_name { get; set; }
        public string flng_ent_last_name { get; set; }
    }
}
