//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_FILINGS_AGGREGATED_Candidate
    {
        public long FILER_ID { get; set; }
        public string CANDIDATEFIRSTNAME { get; set; }
        public string CANDIDATELASTNAME { get; set; }
        public string CANDIDATEMIDDLENAME { get; set; }
        public Nullable<int> OFFICE_TYPE_ID { get; set; }
        public string OFFICE_TYPE_DESC { get; set; }
        public Nullable<int> OFFICE_ID { get; set; }
        public string OFFICE_DESC { get; set; }
        public string DIST_ID { get; set; }
        public Nullable<int> COUNTY_ID { get; set; }
        public string CNTY_DESC { get; set; }
        public Nullable<int> MUNICIPALITY_ID { get; set; }
        public string MUNICIPALITY_DESC { get; set; }
        public int ELECT_YEAR { get; set; }
        public long CAND_ID { get; set; }
        public string CNTY_BOARD { get; set; }
        public Nullable<System.DateTime> SCHED_DATE { get; set; }
    }
}
