//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Filers_Candidate
    {
        public long cand_id { get; set; }
        public string CandidateMasterTypeID { get; set; }
        public string CandidateMasterTypeDescription { get; set; }
        public string CandidateStatus { get; set; }
        public string CandidateStatusDescription { get; set; }
        public Nullable<int> master_type_id { get; set; }
        public string CandidateFirstName { get; set; }
        public string CandidateLastName { get; set; }
        public string CandidateMiddleName { get; set; }
        public string CandidateSuffix { get; set; }
        public string CandAddrStrNum { get; set; }
        public string CandAddrStrName { get; set; }
        public string CandAddr1 { get; set; }
        public string CandAddr2 { get; set; }
        public string CandCity { get; set; }
        public string CandState { get; set; }
        public string CandZip { get; set; }
        public string CandZip4 { get; set; }
        public int OFFICE_ID { get; set; }
        public string office_desc { get; set; }
        public string DIST_ID { get; set; }
        public Nullable<int> county_id { get; set; }
        public string cnty_desc { get; set; }
        public Nullable<int> MUNICIPALITY_ID { get; set; }
        public string municipality_desc { get; set; }
        public string addr_type_desc { get; set; }
        public int BEST_CONTACT_ID { get; set; }
        public string best_contact_desc { get; set; }
        public string master_type_desc { get; set; }
        public string master_lookup_type { get; set; }
        public int OFFICE_TYPE_ID { get; set; }
        public string OFFICE_TYPE_DESC { get; set; }
        public Nullable<System.DateTime> CandidateRegistrationStartDate { get; set; }
        public Nullable<System.DateTime> CandidateTerminationDate { get; set; }
    }
}
