//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Filers_Committee
    {
        public Nullable<int> master_type_id { get; set; }
        public long comm_id { get; set; }
        public string CommitteeMasterTypeID { get; set; }
        public string CommitteeMasterTypeDescription { get; set; }
        public string comm_name { get; set; }
        public string CommitteeStatus { get; set; }
        public string CommitteeStatusDescription { get; set; }
        public string CommitteeHistoryMasterTypeID { get; set; }
        public string CommitteeHistoryMasterTypeDescription { get; set; }
        public string CommAddrStrNum { get; set; }
        public string CommAddrStrName { get; set; }
        public string CommAddr1 { get; set; }
        public string CommAddr2 { get; set; }
        public string CommCity { get; set; }
        public string CommState { get; set; }
        public string CommZip { get; set; }
        public string CommZip4 { get; set; }
        public string TreasurerFirstName { get; set; }
        public string TreasurerLastName { get; set; }
        public string TreasurerMiddleName { get; set; }
        public string TreasurerSuffix { get; set; }
        public string TreasurerAddrStrNum { get; set; }
        public string TreasurerAddrStrName { get; set; }
        public string TreasurerAddr1 { get; set; }
        public string TreasurerAddr2 { get; set; }
        public string TreasurerCity { get; set; }
        public string TreasurerState { get; set; }
        public string TreasurerZip { get; set; }
        public string TreasurerZip4 { get; set; }
        public int OFFICE_ID { get; set; }
        public string office_desc { get; set; }
        public string DIST_ID { get; set; }
        public Nullable<int> county_id { get; set; }
        public string cnty_desc { get; set; }
        public Nullable<int> MUNICIPALITY_ID { get; set; }
        public string municipality_desc { get; set; }
        public Nullable<int> MUNICIPALITY_OFFICE_ID { get; set; }
        public string addr_type_desc { get; set; }
        public int BEST_CONTACT_ID { get; set; }
        public string best_contact_desc { get; set; }
        public string master_type_desc { get; set; }
        public string master_lookup_type { get; set; }
        public int OFFICE_TYPE_ID { get; set; }
        public string OFFICE_TYPE_DESC { get; set; }
        public Nullable<System.DateTime> CommitteeRegistrationStartDate { get; set; }
        public Nullable<System.DateTime> CommitteeTerminationDate { get; set; }
        public int COMM_TYPE_ID { get; set; }
        public string COMM_TYPE_DESC { get; set; }
        public string MASTER_TYPE_ABBREV { get; set; }
    }
}
