//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Notifications
    {
        public Nullable<long> FILING_TRANS_ID { get; set; }
        public long filer_id { get; set; }
        public Nullable<long> COMM_ID { get; set; }
        public Nullable<long> CAND_ID { get; set; }
        public string comm_name { get; set; }
        public string CandidatePrefix { get; set; }
        public string CandidateFirstName { get; set; }
        public string CandidateLastName { get; set; }
        public string CandidateMiddleName { get; set; }
        public string CandidateSuffix { get; set; }
        public Nullable<int> OFFICE_ID { get; set; }
        public string office_desc { get; set; }
        public Nullable<int> OFFICE_TYPE_ID { get; set; }
        public string office_type_desc { get; set; }
        public string dist_id { get; set; }
        public Nullable<int> COUNTY_ID { get; set; }
        public string CNTY_BOARD { get; set; }
        public string subd_desc { get; set; }
        public Nullable<int> MUNICIPALITY_ID { get; set; }
        public string municipality_desc { get; set; }
        public string TreasurerPrefix { get; set; }
        public string TreasurerFirstName { get; set; }
        public string TreasurerLastName { get; set; }
        public string TreasurerMiddleName { get; set; }
        public string TreasurerSuffix { get; set; }
        public string treas_occupation { get; set; }
        public string treas_employer { get; set; }
        public Nullable<int> ELECTION_YEAR_ID { get; set; }
        public Nullable<int> elect_year { get; set; }
        public string elect_type_desc { get; set; }
        public string filing_cat_desc { get; set; }
        public string FILING_CAT_SUBTYPE { get; set; }
        public string filing_desc { get; set; }
        public string filing_abbrev { get; set; }
        public System.DateTime created_date { get; set; }
        public string FILINGS_SOURCE { get; set; }
        public Nullable<System.DateTime> ELECTION_DATE { get; set; }
        public Nullable<System.DateTime> org_date { get; set; }
        public Nullable<System.DateTime> sched_date { get; set; }
        public Nullable<double> org_amt { get; set; }
        public Nullable<System.DateTime> pay_date { get; set; }
        public string pay_number { get; set; }
        public string trans_desc { get; set; }
        public string dist_off_cand_bal_prop { get; set; }
        public string flng_ent_name { get; set; }
        public string flng_ent_first_name { get; set; }
        public string flng_ent_middle_name { get; set; }
        public string flng_ent_last_name { get; set; }
        public string flng_ent_str_num { get; set; }
        public string flng_ent_str_name { get; set; }
        public string flng_ent_addr1 { get; set; }
        public string flng_ent_addr2 { get; set; }
        public string flng_ent_city { get; set; }
        public string flng_ent_state { get; set; }
        public string flng_ent_zip { get; set; }
        public string flng_ent_occupation { get; set; }
        public string flng_ent_employer { get; set; }
    }
}
