//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PetitionRelatedForms
    {
        public long ELECT_CAND_ID { get; set; }
        public Nullable<int> ELECTION_YEAR_ID { get; set; }
        public Nullable<int> ELECT_YEAR { get; set; }
        public Nullable<int> ELECT_TYPE_ID { get; set; }
        public string ELECT_TYPE_DESC { get; set; }
        public int OFFICE_TYPE_ID { get; set; }
        public string OFFICE_TYPE_DESC { get; set; }
        public int OFFICE_ID { get; set; }
        public string OFFICE_DESC { get; set; }
        public string DIST_ID { get; set; }
        public Nullable<int> COUNTY_ID { get; set; }
        public string CNTY_DESC { get; set; }
        public string SUBD_DESC { get; set; }
        public Nullable<int> MUNICIPALITY_ID { get; set; }
        public string MUNICIPALITY_DESC { get; set; }
        public Nullable<int> PARTY_ID { get; set; }
        public string PARTY_DESC { get; set; }
        public string PARTY_SYMBOL { get; set; }
        public string PERSON_PREFIX { get; set; }
        public string PersonFirstName { get; set; }
        public string PersonMiddleName { get; set; }
        public string PersonLastName { get; set; }
        public string PERSON_SUFFIX { get; set; }
        public string addr_str_num { get; set; }
        public string addr_str_name { get; set; }
        public string ADDR_ADDR1 { get; set; }
        public string ADDR_ADDR2 { get; set; }
        public string ADDR_CITY { get; set; }
        public string ADDR_STATE { get; set; }
        public string ADDR_ZIP { get; set; }
        public string addr_zip4 { get; set; }
        public string CandidateFirstName { get; set; }
        public string CandidateMiddleName { get; set; }
        public string CandidateLastName { get; set; }
        public string BALLOT_TYPE_ID { get; set; }
        public string BALLOT_TYPE_DESC { get; set; }
        public string pet_frm_type_desc { get; set; }
        public string pet_frm_type_id { get; set; }
        public string DueDate { get; set; }
        public string DateFiled { get; set; }
        public string DatePostMark { get; set; }
        public string ObjectionFirstName { get; set; }
        public string ObjectionMiddleName { get; set; }
        public string ObjectionLastName { get; set; }
        public string SupportedFirstName { get; set; }
        public string SupportedMiddleName { get; set; }
        public string SupportedLastName { get; set; }
        public string SUPPORTED_ELECT_CAND_ID { get; set; }
        public string SubstituteCandidateFirstName { get; set; }
        public string SubstituteCandidateMiddleName { get; set; }
        public string SubstituteCandidateLastName { get; set; }
    }
}
