//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PartyOrder
    {
        public int ELECTION_YEAR_ID { get; set; }
        public int ELECT_YEAR { get; set; }
        public int PARTY_ID { get; set; }
        public string PARTY_DESC { get; set; }
        public string PARTY_SYMBOL { get; set; }
        public byte[] PARTY_EMBLEM_IMG { get; set; }
        public string R_STATUS { get; set; }
        public string PARTY_COLOR { get; set; }
        public int PARTY_ELECT_ID { get; set; }
        public string PARTY_EMBLEM_DESC { get; set; }
        public Nullable<int> PARENT_PARTY_ID { get; set; }
        public Nullable<int> PARTY_ORDER { get; set; }
        public string PARENT_PARTY_NAME { get; set; }
    }
}
