//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ReviewStatusRpt
    {
        public long REVIEW_FILINGS_ID { get; set; }
        public long REVIEW_FILER_ID { get; set; }
        public int REVIEW_ASSIGN_ID { get; set; }
        public long REVIEW_CORES_ID { get; set; }
        public long REVIEW_COMP_ID { get; set; }
        public string R_EXCLUDE { get; set; }
        public string COMM_NAME { get; set; }
        public int COMM_TYPE_ID { get; set; }
        public string COMM_TYPE_DESC { get; set; }
        public System.DateTime DATE_RECEIVED { get; set; }
        public int FILING_YEAR { get; set; }
        public string DISCLOSURE_PERIOD { get; set; }
        public string AMENDS { get; set; }
        public int NUMBER_OF_LINES { get; set; }
        public int REVIEWER_ID { get; set; }
        public string REVIEWER { get; set; }
        public System.DateTime DATE_ASSIGNED { get; set; }
        public int REVIEW_STATUS_ID { get; set; }
        public string REVIEW_STATUS_DESC { get; set; }
        public string REVIEW_COMPLETE { get; set; }
        public System.DateTime CORRES_MAILED_DATE { get; set; }
        public string CORRES_MAILED_USER { get; set; }
        public string COMM_MAILED_DATE { get; set; }
        public string DAYS_4_DATE { get; set; }
        public string DAYS_7_DATE { get; set; }
        public string DATE_DEFICIENT { get; set; }
        public string DATE_MAILED { get; set; }
        public string CORRESPONDENCE_TYPE { get; set; }
        public string DATE_RETURNED { get; set; }
        public string RETURN_USER { get; set; }
        public string DATE_REISSUED { get; set; }
        public string REISSUE_USER { get; set; }
        public string CORES_RETURN_TYPE_DESC { get; set; }
        public string COMMENT_DATE { get; set; }
        public string COMMENT_DESC { get; set; }
        public string COMMENT_USER { get; set; }
    }
}
