//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_TempDB_FT_QUERY
    {
        public long FILINGS_ID { get; set; }
        public int ELECT_YEAR_ID { get; set; }
        public int OFFICE_TYPE_ID { get; set; }
        public int FILING_TYPE_ID { get; set; }
        public Nullable<int> FILING_CAT_ID { get; set; }
        public string R_STATUS { get; set; }
        public long FILER_ID { get; set; }
        public Nullable<System.DateTime> R_FILING_DATE { get; set; }
        public Nullable<System.DateTime> SUBMIT_DATE { get; set; }
    }
}
