//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPASFIDAS_EFS_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_WhoFiled
    {
        public long ELECT_CAND_ID { get; set; }
        public int ELECTION_YEAR_ID { get; set; }
        public int ELECT_YEAR { get; set; }
        public Nullable<System.DateTime> elect_date { get; set; }
        public int ELECT_TYPE_ID { get; set; }
        public string ELECT_TYPE_DESC { get; set; }
        public int OFFICE_TYPE_ID { get; set; }
        public string OFFICE_TYPE_DESC { get; set; }
        public Nullable<int> OFFICE_ID { get; set; }
        public string OFFICE_DESC { get; set; }
        public string DIST_ID { get; set; }
        public Nullable<int> COUNTY_ID { get; set; }
        public string CNTY_DESC { get; set; }
        public string SUBD_DESC { get; set; }
        public Nullable<int> MUNICIPALITY_ID { get; set; }
        public string MUNICIPALITY_DESC { get; set; }
        public int PARTY_ID { get; set; }
        public string PARTY_DESC { get; set; }
        public string PARTY_SYMBOL { get; set; }
        public string PERSON_PREFIX { get; set; }
        public string PERSON_FIRST_NAME { get; set; }
        public string PERSON_LAST_NAME { get; set; }
        public string PERSON_MIDDLE_NAME { get; set; }
        public string PERSON_SUFFIX { get; set; }
        public string BALLOT_TYPE_DESC { get; set; }
        public string ballot_fname { get; set; }
        public string ballot_mname { get; set; }
        public string ballot_lname { get; set; }
        public string supported_elect_cand_id { get; set; }
        public string SupportedCandidateFirstName { get; set; }
        public string SupportedCandidateMiddleName { get; set; }
        public string SupportedCandidateLastName { get; set; }
        public Nullable<int> PET_TOT_NUM_VOL { get; set; }
        public Nullable<int> PET_TOT_NUM_PGS { get; set; }
        public Nullable<System.DateTime> PET_DATE_RECEIVED { get; set; }
        public Nullable<System.DateTime> PET_POST_MARK_DATE { get; set; }
        public string PET_RECEIVED_BY_USERID { get; set; }
    }
}
